// 지역 가게 섹션: 가게 레지스트리 + 섹션 문자열.
// 새 가게는 shops 배열에 항목을 추가하면 목록/상세 페이지가 자동 생성된다(게임 섹션과 같은 구조).
//
// ⚠️★이 섹션은 **가게의 공식 홈페이지가 아니다.** menewsoft 가 직접 조사해서 쓰는 독립 소개
//   페이지다. 그래서 지켜야 할 규칙이 있다:
//   1) **가게 명의로 공지를 쓰지 않는다.** `news` 는 반드시 출처(source)를 달고, 가게가 한 말이
//      아니라 '어디에 이렇게 보도/기재되어 있다'로 적는다. 가게가 하지 않은 공지를 손님이 믿고
//      움직이면 손님도 가게도 실제 피해를 본다.
//   2) **건의·문의는 가게 전화로 직접 보낸다.** 정적 사이트라 백엔드가 없어서 게시판 글을 받아도
//      사장님께 전달할 방법이 없다. '접수되는 것처럼 보이는' 폼이 제일 나쁘다.
//   3) 가격·영업시간은 **확인 날짜(verified)** 를 함께 표기하고 '방문 전 확인'을 안내한다.
//   4) 사진은 남의 것을 가져오지 않는다. 직접 생성한 일러스트를 쓰고 그렇다고 명시한다.
import type { Lang } from './ui';
import { localizeUrl } from './utils';

/* ===== 섹션 공통 문자열 ===== */
export const shopsUi: Record<Lang, Record<string, string>> = {
  ko: {
    kicker: '지역 가게',
    pageTitle: '지역 가게',
    metaDescription:
      '오래 버틴 동네 가게를 직접 찾아 정리합니다. 메뉴와 가격, 영업시간, 그리고 가기 전에 알아야 할 것들.',
    intro:
      '프랜차이즈가 전국을 덮은 뒤에도 같은 자리에서 같은 방식으로 버티는 가게들이 있습니다. 그런 가게를 하나씩 정리합니다 — 메뉴와 가격, 영업시간, 그리고 헛걸음하지 않도록 미리 알아야 할 것들까지.',
    viewShop: '가게 보기 →',
    backToList: '← 지역 가게 목록',
    sinceLabel: '개업',
    newsTitle: '최근 소식',
    menuTitle: '메뉴',
    prideTitle: '이 메뉴의 강점',
    visitTitle: '가기 전에',
    contactTitle: '건의·문의',
    disclaimerTitle: '이 페이지에 대하여',
    callNow: '전화하기',
    verifiedPrefix: '확인 시점',
    priceNote: '가격·영업시간은 바뀔 수 있습니다. 방문 전 전화로 확인하세요.',
    illustNote: '이 페이지의 그림은 분위기를 전하기 위해 직접 생성한 AI 일러스트입니다. 실제 가게의 음식·매장 사진이 아닙니다.',
    sourceLabel: '출처',
    contactLead: '가게에 하실 말씀은 가게로 직접 전해 주세요. 이 페이지는 menewsoft 가 만든 독립 소개 페이지라, 여기 남기신 글은 사장님께 전달되지 않습니다.',
    correctionPre: '이 소개 내용에서 틀린 부분(가격·영업시간 변경 등)을 발견하셨다면',
    correctionLink: 'menewsoft 로 알려주세요',
    correctionPost: '. 확인해서 고치겠습니다.',
    takedownTitle: '가게 관계자분께',
    takedownBody: '이 페이지의 게재를 원하지 않으시면 알려만 주세요. 이유를 여쭙지 않고 바로 내려드립니다.',
    takedownLink: '게재 중단 요청하기',
    notOfficial: '이 페이지는 {name}의 공식 홈페이지가 아닙니다. menewsoft 가 공개된 자료를 모아 정리한 독립 소개 페이지이며, 가게와 아무런 관계가 없고 광고·협찬을 받지 않았습니다.',
  },
  en: {
    kicker: 'LOCAL SHOPS',
    pageTitle: 'Local Shops',
    metaDescription:
      'Long-running neighbourhood shops in Korea, researched and written up first-hand: menus, prices, hours and what to know before you go.',
    intro:
      'Some shops keep doing the same thing in the same place long after the franchises took over. We write them up one by one — menu, prices, hours, and the things you need to know so you do not make a wasted trip.',
    viewShop: 'View shop →',
    backToList: '← All shops',
    sinceLabel: 'Since',
    newsTitle: 'Latest',
    menuTitle: 'Menu',
    prideTitle: 'Why this one',
    visitTitle: 'Before you go',
    contactTitle: 'Feedback',
    disclaimerTitle: 'About this page',
    callNow: 'Call',
    verifiedPrefix: 'Verified',
    priceNote: 'Prices and hours change. Please call ahead.',
    illustNote: 'Illustrations on this page were generated by us to set the mood. They are not photographs of the actual shop or its food.',
    sourceLabel: 'Source',
    contactLead: 'Anything you want to say to the shop should go to the shop directly. This is an independent write-up by menewsoft — anything left here does not reach the owner.',
    correctionPre: 'If something here is wrong (a price or opening hours have changed),',
    correctionLink: 'let menewsoft know',
    correctionPost: ' and we will check and fix it.',
    takedownTitle: 'If you run this shop',
    takedownBody: 'If you would rather this page did not exist, just tell us. We will take it down, and we will not ask why.',
    takedownLink: 'Request removal',
    notOfficial: 'This is not the official website of {name}. It is an independent write-up compiled by menewsoft from publicly available sources. We have no relationship with the shop and received no payment or sponsorship.',
  },
  ja: {
    kicker: 'ローカル店',
    pageTitle: 'ローカル店',
    metaDescription: '長く続く韓国の街の名店を自分たちで調べてまとめます。メニュー、価格、営業時間、行く前に知っておくこと。',
    intro: 'チェーン店が広がった後も、同じ場所で同じやり方を守る店があります。そんな店を一軒ずつ紹介します。',
    viewShop: '店を見る →', backToList: '← 一覧へ', sinceLabel: '創業', newsTitle: '最新情報',
    menuTitle: 'メニュー', prideTitle: 'この一品の強み', visitTitle: '行く前に', contactTitle: 'ご意見',
    disclaimerTitle: 'このページについて', callNow: '電話する', verifiedPrefix: '確認時点',
    priceNote: '価格・営業時間は変わることがあります。訪問前に電話でご確認ください。',
    illustNote: 'このページの画像は雰囲気を伝えるために生成したAIイラストです。実際の店舗・料理の写真ではありません。',
    sourceLabel: '出典',
    contactLead: 'お店へのご要望はお店へ直接お伝えください。このページは menewsoft が独自にまとめた紹介ページのため、ここに書かれた内容は店主に届きません。',
    correctionPre: '記載に誤り（価格・営業時間の変更など）がありましたら',
    correctionLink: 'menewsoft までお知らせください',
    correctionPost: '。確認のうえ修正いたします。',
    takedownTitle: '店舗関係者の方へ',
    takedownBody: 'このページの掲載をご希望されない場合は、お知らせいただくだけで結構です。理由を伺うことなく取り下げます。',
    takedownLink: '掲載の取り下げを依頼する',
    notOfficial: 'このページは {name} の公式サイトではありません。menewsoft が公開情報をもとに独自にまとめた紹介ページであり、店舗とは一切関係がなく、広告・協賛も受けていません。',
  },
  es: {
    kicker: 'LOCALES DE BARRIO',
    pageTitle: 'Locales de barrio',
    metaDescription: 'Locales coreanos de toda la vida, investigados de primera mano: carta, precios, horarios y lo que hay que saber antes de ir.',
    intro: 'Hay locales que siguen haciendo lo mismo en el mismo sitio mucho después de que llegaran las cadenas. Los vamos contando uno a uno.',
    viewShop: 'Ver local →', backToList: '← Todos los locales', sinceLabel: 'Desde', newsTitle: 'Novedades',
    menuTitle: 'Carta', prideTitle: 'Por qué este', visitTitle: 'Antes de ir', contactTitle: 'Sugerencias',
    disclaimerTitle: 'Sobre esta página', callNow: 'Llamar', verifiedPrefix: 'Verificado',
    priceNote: 'Los precios y horarios cambian. Llama antes de ir.',
    illustNote: 'Las ilustraciones de esta página las generamos nosotros. No son fotos del local ni de su comida.',
    sourceLabel: 'Fuente',
    contactLead: 'Lo que quieras decirle al local, díselo directamente. Esta es una ficha independiente de menewsoft: lo que escribas aquí no llega al dueño.',
    correctionPre: 'Si algo es incorrecto (un precio o un horario ha cambiado),',
    correctionLink: 'avisa a menewsoft',
    correctionPost: ' y lo comprobaremos y corregiremos.',
    takedownTitle: 'Si regentas este local',
    takedownBody: 'Si prefieres que esta página no exista, solo tienes que decírnoslo. La retiramos sin preguntar por qué.',
    takedownLink: 'Solicitar la retirada',
    notOfficial: 'Esta no es la web oficial de {name}. Es una ficha independiente elaborada por menewsoft a partir de fuentes públicas. No tenemos ninguna relación con el local ni hemos recibido pago o patrocinio.',
  },
  zh: {
    kicker: '本地老店',
    pageTitle: '本地老店',
    metaDescription: '亲自走访整理的韩国老字号小店：菜单、价格、营业时间，以及出发前该知道的事。',
    intro: '连锁店铺开遍全国之后，仍有一些店在同一个地方用同样的做法坚持着。我们一家一家记录下来。',
    viewShop: '查看店铺 →', backToList: '← 返回列表', sinceLabel: '创立', newsTitle: '最新动态',
    menuTitle: '菜单', prideTitle: '这道菜的看点', visitTitle: '出发前', contactTitle: '意见反馈',
    disclaimerTitle: '关于本页', callNow: '拨打电话', verifiedPrefix: '核实时间',
    priceNote: '价格与营业时间可能变动，前往前请先致电确认。',
    illustNote: '本页插图为我们生成的 AI 插画，并非该店实际菜品或门店照片。',
    sourceLabel: '来源',
    contactLead: '如需向店家反映，请直接联系店家。本页是 menewsoft 独立整理的介绍页面，在此留言不会传达给店主。',
    correctionPre: '若本页内容有误（价格或营业时间变动等），',
    correctionLink: '请告知 menewsoft',
    correctionPost: '，我们会核实并更正。',
    takedownTitle: '致店家',
    takedownBody: '若您不希望本页继续展示，只需告知我们。我们会立即撤下，且不会追问原因。',
    takedownLink: '申请撤下本页',
    notOfficial: '本页并非 {name} 的官方网站，而是 menewsoft 根据公开资料独立整理的介绍页面。我们与该店没有任何关系，也未收取广告或赞助费用。',
  },
};

/* ===== 지역·업종 분류 =====
   ⚠️분류 코드는 **자유 문자열이 아니라 코드**다. 디렉토리 필터·검색 인덱스가 이 코드로 묶이기
   때문에 '강원 원주'/'강원도 원주시'처럼 표기가 흔들리면 같은 지역이 두 칸으로 쪼개진다.
   시·군(city)만 자유 문자열로 둔다. */
export const REGIONS = ['seoul', 'gyeonggi', 'gangwon'] as const;
export type RegionCode = (typeof REGIONS)[number];

export const CATEGORIES = ['food', 'cafe', 'beauty', 'academy', 'repair', 'etc'] as const;
export type CategoryCode = (typeof CATEGORIES)[number];

export const regionLabels: Record<RegionCode, Partial<Record<Lang, string>> & { ko: string }> = {
  seoul: { ko: '서울', en: 'Seoul', ja: 'ソウル', es: 'Seúl', zh: '首尔' },
  gyeonggi: { ko: '경기도', en: 'Gyeonggi', ja: '京畿道', es: 'Gyeonggi', zh: '京畿道' },
  gangwon: { ko: '강원도', en: 'Gangwon', ja: '江原道', es: 'Gangwon', zh: '江原道' },
};

export const categoryLabels: Record<CategoryCode, Partial<Record<Lang, string>> & { ko: string }> = {
  food: { ko: '음식점', en: 'Restaurants', ja: '飲食店', es: 'Restaurantes', zh: '餐厅' },
  cafe: { ko: '카페·베이커리', en: 'Cafés & bakeries', ja: 'カフェ', es: 'Cafeterías', zh: '咖啡·烘焙' },
  beauty: { ko: '미용·이용', en: 'Hair & beauty', ja: '美容', es: 'Peluquería', zh: '美容' },
  academy: { ko: '학원·교습', en: 'Academies', ja: '学習塾', es: 'Academias', zh: '培训' },
  repair: { ko: '수리·정비', en: 'Repair', ja: '修理', es: 'Reparación', zh: '维修' },
  etc: { ko: '그 밖의 업종', en: 'Other', ja: 'その他', es: 'Otros', zh: '其他' },
};

export function regionLabel(code: RegionCode, lang: Lang): string {
  return regionLabels[code][lang] ?? regionLabels[code].ko;
}
export function categoryLabel(code: CategoryCode, lang: Lang): string {
  return categoryLabels[code][lang] ?? categoryLabels[code].ko;
}

/* ===== 데이터 모델 ===== */
export interface MenuItem {
  name: string;
  price: string;
  /** 이 메뉴를 왜 시키는가 — 조리법·재료·식감 근거로. 과장 금지. */
  pride: string;
  /** 처음 온 사람에게 추천하는 순서(1이 가장 먼저) */
  rank?: number;
}
export interface NewsItem {
  date: string;
  text: string;
  /** ⚠️**필수**(타입 강제) — 가게 명의 공지가 아니라 '어디에 이렇게 나와 있다'임을 밝힌다.
   *  출처 없는 소식은 우리가 지어낸 말이 되고, 손님이 그걸 믿고 헛걸음하면 가게가 피해를 본다.
   *  출처를 못 찾으면 **쓰지 않는다**. 그래서 optional 이 아니라 required 다(빠지면 빌드 실패). */
  source: { label: string; url: string };
}
export interface ShopCopy {
  name: string;
  tagline: string;
  /** 히어로 아래 본문(문단 배열) */
  story: string[];
  menu: MenuItem[];
  /** 방문 정보(라벨/값) */
  visit: { label: string; value: string }[];
  /** 가기 전 주의사항 */
  tips: string[];
  news: NewsItem[];
}
export interface ShopEntry {
  slug: string;
  /** 광역 지역 코드(필터 단위) */
  region: RegionCode;
  /** 시·군 — 표시·검색용. 예: '원주' */
  city: string;
  /** 업종 코드(필터 단위) */
  category: CategoryCode;
  /** 업종 세부 표기. 예: '통닭' — 필터에는 안 쓰고 카드·검색어에만 쓴다 */
  categoryDetail?: string;
  since: string;
  /** 확인 날짜 — 가격·영업시간이 언제 기준인지 */
  verified: string;
  cover: string;
  images: string[];
  tel: string;
  mapUrl: string;
  sources: { label: string; url: string }[];
  copy: Partial<Record<Lang, ShopCopy>> & { ko: ShopCopy };
}

export const shops: ShopEntry[] = [
  {
    slug: 'boritgogae-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '보리밥',
    since: '',
    verified: '2026-08-11',
    cover: '/blog-assets/boritgogae-wonju/img_00.png',
    images: ['/blog-assets/boritgogae-wonju/img_01.png'],
    tel: '033-747-8289',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%EB%B3%B4%EB%A6%BF%EA%B3%A0%EA%B0%9C',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=ePZRLbnFDaPn' },
      { label: '카카오맵', url: 'https://m.map.kakao.com/actions/searchView?q=%EC%9B%90%EC%A3%BC%20%EB%B3%B4%EB%A6%BF%EA%B3%A0%EA%B0%9C' },
    ],
    copy: {
      ko: {
        name: '보릿고개',
        tagline: '혁신도시 한복판에서 보리밥 한 상, 가격 만족도가 유난히 높은 집',
        story: [
          '반곡동 혁신도시는 원주에서 가장 늦게 생긴 동네입니다. 새 건물과 프랜차이즈가 먼저 들어선 자리인데, 그 사이 H타워 1층 안쪽에 보리밥 한 상을 차리는 집이 있습니다.',
          '보리밥은 원래 쌀이 모자라던 시절의 음식입니다. 가게 이름도 거기서 왔습니다. 지금은 잡곡의 식감과 나물 반찬을 함께 먹는 정식으로 남았습니다.',
          '두 곳의 평가가 드물게 일치합니다. 다이닝코드 4.6(31건), 카카오맵 4.4(259건). 특히 다이닝코드 항목별 점수에서 가격 만족이 4.9, 위생이 5.0으로 맛(4.8)보다 높습니다. 분위기 태그도 푸짐함과 가성비가 가장 많이 붙었습니다.',
        ],
        menu: [
          {
            name: '보리밥정식',
            price: '15,000원 (2인 이상 주문)',
            rank: 1,
            pride:
              '이 집의 전부입니다. 보리밥에 들깨삼계탕·녹두전·도토리묵·우렁이초무침·청국장과 비빔찬이 함께 나옵니다. ⚠️메뉴판에는 15,000원으로 적혀 있는데 같은 페이지의 구성 설명에는 1인 11,000원이라고 되어 있어 가격 표기가 엇갈립니다. 주문 전 확인하세요.',
          },
          {
            name: '녹두전',
            price: '4개 6,000원 · 8개 10,000원',
            rank: 2,
            pride: '정식에 포함되지만 따로 더 시킬 수 있습니다. 여럿이 갔을 때 추가하는 항목입니다.',
          },
          {
            name: '도토리묵무침 · 우렁이초무침',
            price: '각 11,000원 (소 6,000원)',
            pride: '정식 구성에 들어가는 반찬을 단품으로도 팝니다. 술자리용으로 시키는 조합입니다.',
          },
          {
            name: '인덕주',
            price: '잔 2,000원 · 소 6,000원 · 대 10,000원',
            pride: '인삼과 더덕을 갈아 넣은 동동주라고 표기되어 있습니다. 이 집에서만 쓰는 이름입니다.',
          },
          {
            name: '들깨백숙 추가',
            price: '반마리 8,000원 · 한마리 15,000원',
            pride: '정식에 들어가는 들깨삼계탕을 더 넣는 선택지입니다.',
          },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 혁신로 19 H타워 1층 (반곡동 1860-5)' },
          { label: '전화', value: '033-747-8289' },
          { label: '영업', value: '11:00~21:00 (브레이크타임 15:00~17:00, 라스트오더 20:00)' },
          { label: '휴무', value: '화요일' },
          { label: '주차', value: '무료주차 (후기 19건에서 언급)' },
        ],
        tips: [
          '보리밥정식은 2인 이상부터 주문할 수 있습니다. 혼자 가면 이 집의 주력 메뉴를 못 시킵니다.',
          '오후 3시부터 5시까지 브레이크타임입니다. 늦은 점심으로 가면 문이 닫혀 있습니다.',
          '화요일 휴무입니다.',
          '보리밥정식 가격이 자료 안에서 15,000원과 11,000원으로 엇갈립니다. 인원수와 가격을 전화로 확인하고 가세요.',
          '혁신도시 H타워 1층 안쪽, 수변 방향입니다. 건물 앞에서 바로 보이지 않습니다.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: '확인 시점 기준 영업시간은 11:00~21:00, 브레이크타임 15:00~17:00, 라스트오더 20:00이며 화요일이 휴무로 표시되어 있습니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=ePZRLbnFDaPn' },
          },
        ],
      },
      en: {
        name: 'Boritgogae',
        tagline: 'A full barley-rice spread in the middle of Wonju’s newest district',
        story: [
          'Banggok-dong is the newest part of Wonju — new buildings, chain outlets. Tucked inside the ground floor of H Tower is a place serving barley rice the old way.',
          'Barley rice was what people ate when rice was short; the shop is named after that period. Today it arrives as a set with stews, pancakes and a spread of vegetable sides.',
          'Both review platforms agree, which is rare: 4.6 from 31 on DiningCode, 4.4 from 259 on Kakao Map. Value for money scores 4.9 — higher than the food score itself.',
        ],
        menu: [
          { name: 'Barley rice set', price: '₩15,000 (min. 2 people)', rank: 1, pride: 'Barley rice with perilla chicken soup, mung bean pancake, acorn jelly, snail salad and fermented soybean stew. Note: sources list both ₩15,000 and ₩11,000 — please confirm.' },
          { name: 'Mung bean pancake', price: '₩6,000 / ₩10,000', rank: 2, pride: 'Included in the set, orderable as an extra.' },
          { name: 'Acorn jelly / snail salad', price: '₩11,000 each', pride: 'Set components sold à la carte, usually with drinks.' },
          { name: 'Indeokju (house rice wine)', price: '₩2,000–10,000', pride: 'Listed as makgeolli infused with ginseng and deodeok root.' },
        ],
        visit: [
          { label: 'Address', value: '19 Hyeoksin-ro, H Tower 1F, Wonju, Gangwon' },
          { label: 'Phone', value: '033-747-8289' },
          { label: 'Hours', value: '11:00–21:00 (break 15:00–17:00, last order 20:00)' },
          { label: 'Closed', value: 'Tuesdays' },
        ],
        tips: [
          'The barley rice set needs a minimum of two people — solo diners cannot order the main dish.',
          'Closed 15:00–17:00 for a break.',
          'Set price is listed inconsistently across sources. Call to confirm.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: 'Hours listed as 11:00–21:00 with a 15:00–17:00 break; closed Tuesdays.',
            source: { label: 'DiningCode', url: 'https://www.diningcode.com/profile.php?rid=ePZRLbnFDaPn' },
          },
        ],
      },
    },
  },
  {
    slug: 'heungeop-mukjip-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '묵밥',
    since: '',
    verified: '2026-08-11',
    cover: '/blog-assets/heungeop-mukjip-wonju/img_00.png',
    images: ['/blog-assets/heungeop-mukjip-wonju/img_01.png'],
    tel: '033-763-5533',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%ED%9D%A5%EC%97%85%EB%AC%B5%EC%A7%91',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=LN4FDAy83o0i' },
      { label: '카카오맵', url: 'https://m.map.kakao.com/actions/searchView?q=%EC%9B%90%EC%A3%BC%20%ED%9D%A5%EC%97%85%EB%AC%B5%EC%A7%91' },
    ],
    copy: {
      ko: {
        name: '흥업묵집',
        tagline: '메밀묵 하나로 아침 아홉 시에 문을 여는 흥업면 묵집',
        story: [
          '흥업면은 원주 도심에서 남쪽으로 내려간 곳입니다. 관광 동선이 아니라 지나가는 길에 가까운 동네인데, 여기 메밀묵을 주로 하는 집이 있습니다.',
          '묵은 원래 강원도에서 흔했던 음식입니다. 메밀을 갈아 쑤어 굳힌 뒤 썰어 국물에 말거나 무쳐 먹습니다. 재료가 단순해서 손맛과 배합이 그대로 드러나는 종류입니다.',
          '다이닝코드는 4.5(8건), 카카오맵은 4.2(30건)로 두 곳 모두 높습니다. 다이닝코드 항목별로는 위생 5.0, 맛 4.8입니다. 〈생활의 달인〉에 소개된 곳으로 기재되어 있습니다.',
        ],
        menu: [
          {
            name: '메밀묵',
            price: '9,000원',
            rank: 1,
            pride:
              '이 집의 기준입니다. 묵을 굵게 썰어 국물에 말아 냅니다. 재료가 메밀과 국물뿐이라 첫 방문에 이 집을 판단하기 가장 쉬운 메뉴입니다.',
          },
          {
            name: '메밀전병',
            price: '7,000원',
            rank: 2,
            pride: '메밀 반죽을 얇게 부쳐 소를 넣고 말아 썬 것입니다. 묵과 함께 시켜 나눠 먹는 조합으로 후기에 자주 나옵니다.',
          },
          { name: '메밀전', price: '6,000원', rank: 3, pride: '가장 저렴한 곁들임입니다. 메밀 반죽 그대로의 맛을 보는 쪽입니다.' },
          { name: '메밀묵 한 모', price: '11,000원', pride: '썰지 않은 묵 한 모입니다. 포장해 가는 사람들이 시킵니다.' },
          { name: '묵무침', price: '15,000원', pride: '묵을 채소와 함께 양념에 무친 것으로, 여럿이 갔을 때의 선택지입니다.' },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 흥업면 남원로 29-3 (흥업리 546-8)' },
          { label: '전화', value: '033-763-5533 (카카오맵) · 033-762-4210 (다이닝코드)' },
          { label: '영업', value: '09:00~20:00 (브레이크타임 15:00~17:00, 라스트오더 14:30·19:30)' },
          { label: '휴무', value: '월요일 (방문 후기 기준)' },
          { label: '주차', value: '무료주차' },
        ],
        tips: [
          '⚠️전화번호가 자료마다 다릅니다. 카카오맵은 033-763-5533, 다이닝코드는 033-762-4210으로 적혀 있습니다. 어느 쪽이 현재 번호인지 확인하지 못했으니 둘 다 시도해 보세요.',
          '아침 9시에 엽니다. 원주에서 이른 아침 식사가 되는 집이 많지 않습니다.',
          '오후 3시부터 5시까지 브레이크타임이고, 라스트오더는 점심 14:30 · 저녁 19:30입니다.',
          '월요일 휴무는 방문 후기에서 확인한 것으로 공식 표기가 아닙니다. 월요일에 가신다면 전화로 확인하세요.',
          '흥업면은 원주 도심에서 차로 이동해야 합니다. 시내 일정에 끼워 넣기보다 목적지로 잡는 편이 낫습니다.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: '확인 시점 기준 영업시간은 09:00~20:00, 브레이크타임 15:00~17:00으로 기재되어 있습니다. 전화번호는 자료에 따라 두 가지로 나와 있어 방문 전 확인이 필요합니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=LN4FDAy83o0i' },
          },
          {
            date: '방영 시점 미상',
            text: '〈생활의 달인〉에 소개된 곳으로 기재되어 있습니다. 방영 회차와 날짜는 확인하지 못했습니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=LN4FDAy83o0i' },
          },
        ],
      },
      en: {
        name: 'Heungeop Mukjip',
        tagline: 'Buckwheat jelly, served from nine in the morning in Heungeop-myeon',
        story: [
          'Heungeop-myeon sits south of central Wonju — a place you pass through rather than visit. This shop works almost entirely in buckwheat jelly.',
          'Muk is old Gangwon food: buckwheat ground, cooked to a set, then sliced into broth or dressed as a salad. With so few ingredients, there is nowhere to hide.',
          'DiningCode rates it 4.5 from 8, Kakao Map 4.2 from 30. Hygiene scores 5.0. It is recorded as having appeared on the TV programme “Life’s Master”.',
        ],
        menu: [
          { name: 'Buckwheat jelly in broth', price: '₩9,000', rank: 1, pride: 'The house baseline — thick-cut jelly in cold broth. The easiest way to judge the kitchen.' },
          { name: 'Buckwheat crepe rolls', price: '₩7,000', rank: 2, pride: 'Thin buckwheat crepes rolled around a savoury filling and sliced. Frequently ordered alongside the jelly.' },
          { name: 'Buckwheat pancake', price: '₩6,000', rank: 3, pride: 'The cheapest side; buckwheat batter on its own.' },
          { name: 'Dressed jelly salad', price: '₩15,000', pride: 'Jelly tossed with vegetables — for a group.' },
        ],
        visit: [
          { label: 'Address', value: '29-3 Namwon-ro, Heungeop-myeon, Wonju, Gangwon' },
          { label: 'Phone', value: '033-763-5533 (Kakao) / 033-762-4210 (DiningCode)' },
          { label: 'Hours', value: '09:00–20:00 (break 15:00–17:00)' },
          { label: 'Closed', value: 'Mondays (per visitor reviews)' },
        ],
        tips: [
          'Two different phone numbers appear across sources — we could not confirm which is current.',
          'Opens at 9am, unusually early for the area.',
          'The Monday closure comes from reviews, not an official listing. Call if you are going on a Monday.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: 'Hours listed as 09:00–20:00 with a 15:00–17:00 break. Two different phone numbers are listed across sources.',
            source: { label: 'DiningCode', url: 'https://www.diningcode.com/profile.php?rid=LN4FDAy83o0i' },
          },
        ],
      },
    },
  },
  {
    slug: 'geumdae-jjamppong-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '짬뽕',
    since: '',
    verified: '2026-08-11',
    cover: '/blog-assets/geumdae-jjamppong-wonju/img_00.png',
    images: ['/blog-assets/geumdae-jjamppong-wonju/img_01.png'],
    tel: '033-765-8486',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%EA%B8%88%EB%8C%80%EC%A7%AC%EB%BD%95',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=6bkyjeIXQi5H' },
      { label: '카카오맵', url: 'https://m.map.kakao.com/actions/searchView?q=%EC%9B%90%EC%A3%BC%20%EA%B8%88%EB%8C%80%EC%A7%AC%EB%BD%95' },
    ],
    copy: {
      ko: {
        name: '금대짬뽕',
        tagline: '치악산 금대계곡 가는 길, 마당 넓은 산자락 중국집',
        story: [
          '판부면 금대리는 치악산 남쪽 자락입니다. 금대계곡으로 들어가는 길목이고, 도심에서 차로 나가야 하는 위치입니다. 이 집은 그 길가에 있습니다.',
          '중국집이지만 시내 상가의 그것과는 다릅니다. 다이닝코드에 붙은 태그가 계곡·야외테라스·넓은마당입니다. 식당 아래로 계곡이 이어져 있어 여름에 아이들과 함께 오기 좋다는 후기가 있습니다.',
          '다이닝코드 4.8(4건), 카카오맵 4.6(14건)으로 양쪽 모두 높지만 ⚠️표본이 작습니다. 평가가 굳어졌다고 보기는 이른 단계입니다.',
        ],
        menu: [
          {
            name: '해물짬뽕',
            price: '10,000원',
            rank: 1,
            pride: '가게 이름이 곧 대표 메뉴입니다. 처음이라면 이것부터 시켜 이 집의 기준을 보는 게 맞습니다.',
          },
          {
            name: '낙지해물짬뽕 · 차돌해물짬뽕',
            price: '각 13,000원',
            rank: 2,
            pride: '기본 짬뽕에 낙지나 차돌박이를 얹은 것입니다. 3,000원 차이라 두 번째 방문에 고르기 좋은 선택지입니다.',
          },
          { name: '짜장면', price: '7,000원', rank: 3, pride: '이 집에서 가장 싼 한 그릇입니다. 간짜장은 10,000원입니다.' },
          { name: '탕수육', price: '(소) 20,000원', pride: '여럿이 왔을 때 짬뽕과 함께 시키는 조합입니다.' },
          { name: '볶음밥 · 잡채밥', price: '9,000원 · 10,000원', pride: '면이 부담스럽거나 아이와 함께일 때의 밥 메뉴입니다.' },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 판부면 치악로 689-12 (금대리 189-34)' },
          { label: '전화', value: '033-765-8486' },
          { label: '영업', value: '10:00~19:00' },
          { label: '휴무', value: '공개 자료에 표시 없음 — 전화 확인 권장' },
          { label: '주차', value: '무료주차 · 넓은 마당' },
        ],
        tips: [
          '저녁 7시에 닫습니다. 산자락이라 해가 지면 이동도 어두워지니 낮 시간에 가는 편이 낫습니다.',
          '도심이 아닙니다. 치악로를 따라 금대리 방향으로 나가야 하며, 차 없이 가기는 어렵습니다.',
          '여름에는 계곡을 함께 찾는 사람이 많아 식사 시간대가 몰릴 수 있습니다.',
          '평가 표본이 작습니다(카카오맵 14건). 널리 검증된 집이라기보다 아직 알려지는 중인 곳으로 보시는 게 맞습니다.',
          '휴무일이 어느 자료에도 없습니다. 멀리서 가신다면 전화가 확실합니다.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: '확인 시점 기준 영업시간은 매일 10:00~19:00으로 기재되어 있으며 휴무일 표시는 없습니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=6bkyjeIXQi5H' },
          },
        ],
      },
      en: {
        name: 'Geumdae Jjamppong',
        tagline: 'A Korean-Chinese kitchen with a wide yard, on the road to Geumdae valley',
        story: [
          'Geumdae-ri sits on the southern skirt of Chiaksan, on the way into Geumdae valley. You need a car to get here.',
          'It is a Korean-Chinese restaurant, but not the kind found in a city arcade — the listing tags are “valley”, “terrace”, “wide yard”. A stream runs below the restaurant.',
          'DiningCode rates it 4.8 from 4 and Kakao Map 4.6 from 14 — high on both, but from a small sample.',
        ],
        menu: [
          { name: 'Seafood jjamppong', price: '₩10,000', rank: 1, pride: 'The name of the shop is the dish. Start here.' },
          { name: 'Octopus / brisket jjamppong', price: '₩13,000 each', rank: 2, pride: 'The base bowl with octopus or beef brisket added.' },
          { name: 'Jajangmyeon', price: '₩7,000', rank: 3, pride: 'The cheapest bowl on the menu.' },
          { name: 'Sweet and sour pork', price: '₩20,000 (small)', pride: 'The usual group order alongside the noodles.' },
        ],
        visit: [
          { label: 'Address', value: '689-12 Chiak-ro, Panbu-myeon, Wonju, Gangwon' },
          { label: 'Phone', value: '033-765-8486' },
          { label: 'Hours', value: '10:00–19:00' },
          { label: 'Closed', value: 'Not stated in public sources — please call' },
        ],
        tips: [
          'Closes at 19:00, and the drive back is dark. Go during the day.',
          'This is not in town. You need a car.',
          'The rating sample is small (14 on Kakao Map) — treat it as promising rather than proven.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: 'Hours listed as 10:00–19:00 daily, with no closing day stated.',
            source: { label: 'DiningCode', url: 'https://www.diningcode.com/profile.php?rid=6bkyjeIXQi5H' },
          },
        ],
      },
    },
  },
  {
    slug: 'ujeongjip-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '분식',
    since: '',
    verified: '2026-08-11',
    cover: '/blog-assets/ujeongjip-wonju/img_00.png',
    images: ['/blog-assets/ujeongjip-wonju/img_01.png'],
    tel: '033-743-5822',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%EC%9A%B0%EC%A0%95%EC%A7%91',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=qSeAPfgfMxtH' },
      { label: '카카오맵', url: 'https://m.map.kakao.com/actions/searchView?q=%EC%9B%90%EC%A3%BC%20%EC%9A%B0%EC%A0%95%EC%A7%91' },
    ],
    copy: {
      ko: {
        name: '우정집',
        tagline: '자유시장 지하, 떡볶이 1인분 4,000원짜리 분식집',
        story: [
          '원주 중앙동 자유시장 지하에는 분식집이 여럿 있습니다. 우정집은 그중 한 곳으로, 지하 1층 안쪽에 있습니다.',
          '메뉴가 떡볶이·순대·튀김·김밥으로 단순합니다. 떡볶이 1인분이 4,000원, 김밥 한 줄이 2,500원, 튀김이 개당 1,000원입니다. 시장 분식의 가격대가 그대로 남아 있는 편입니다.',
          '다이닝코드 4.5(5건), 카카오맵 4.1(24건)입니다. 다이닝코드 분위기 태그에서 가장 많이 붙은 것이 “지역주민이 찾는”입니다. 방문 목적도 간식과 혼밥이 상위입니다.',
        ],
        menu: [
          {
            name: '떡볶이',
            price: '1인분 4,000원 · 2인분 7,000원 · 포장 5,000원',
            rank: 1,
            pride:
              '이 집의 기준입니다. 후기에서 반복해서 나오는 표현이 달달하다는 것입니다. 매운맛으로 미는 계열이 아닙니다.',
          },
          {
            name: '튀김',
            price: '개당 1,000원 (만두튀김은 4개 1,000원)',
            rank: 2,
            pride: '김말이·오징어·고구마를 낱개로 고릅니다. 떡볶이 국물에 적셔 먹는 조합이 시장 분식의 기본입니다.',
          },
          { name: '순대', price: '8,000원 (포장 9,000원)', rank: 3, pride: '떡볶이와 함께 시키는 두 번째 축입니다.' },
          { name: '김밥', price: '2,500원', pride: '한 줄 기준입니다. 혼자 간단히 먹을 때의 조합입니다.' },
          { name: '어묵', price: '2개 1,000원', pride: '서서 먹고 나가는 손님이 많은 항목입니다.' },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 중앙시장길 11 자유시장 지하 1층 (중앙동 57)' },
          { label: '전화', value: '033-743-5822' },
          { label: '영업', value: '⚠️공식 표기 없음 — 방문 후기 기준 11:00~19:30' },
          { label: '휴무', value: '⚠️미확인 — 후기에는 매달 1·3번째 일요일 휴무로 적혀 있음' },
          { label: '주차', value: '자유시장 공영주차장' },
        ],
        tips: [
          '★떡볶이가 떨어지면 그날은 끝입니다. 오후 5시쯤 이미 바닥을 보이기 시작했다는 후기가 있습니다. 떡볶이가 목적이라면 이른 시간에 가세요.',
          '⚠️영업시간이 공식적으로 확인되지 않습니다. 다이닝코드에는 “영업시간 확인 필요”로 표시되어 있고, 후기마다 조금씩 다릅니다. 먼 길이면 전화가 확실합니다.',
          '지하 1층이라 지상에서는 보이지 않습니다. 자유시장 안으로 들어가 지하로 내려가야 합니다.',
          '매장이 작은 편이라 앉아서 먹기보다 포장이 편하다는 후기가 있습니다.',
          '시장 공영주차장을 이용하게 됩니다. 시장 골목에 차를 대기는 어렵습니다.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: '확인 시점 기준 다이닝코드에 영업시간이 “확인 필요”로 표시되어 있습니다. 방문 후기에는 11:00~19:30, 매달 1·3번째 일요일 휴무로 적혀 있으나 공식 표기는 아닙니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=qSeAPfgfMxtH' },
          },
        ],
      },
      en: {
        name: 'Ujeongjip',
        tagline: 'Underground in Jayu Market — tteokbokki at ₩4,000 a portion',
        story: [
          'There are several snack stalls in the basement of Jayu Market in central Wonju. Ujeongjip is one of them, tucked inside the lower floor.',
          'The menu is short: rice cakes, blood sausage, fritters, seaweed rolls. A portion of tteokbokki is ₩4,000, a seaweed roll ₩2,500, fritters ₩1,000 each — market prices, more or less unchanged.',
          'DiningCode rates it 4.5 from 5, Kakao Map 4.1 from 24. The most common descriptor on DiningCode is “where locals go”.',
        ],
        menu: [
          { name: 'Tteokbokki', price: '₩4,000 / ₩7,000 / ₩5,000 takeaway', rank: 1, pride: 'The baseline. Reviews describe it as sweet-leaning rather than fiery.' },
          { name: 'Fritters', price: '₩1,000 each', rank: 2, pride: 'Picked individually — seaweed rolls, squid, sweet potato — and dipped in the tteokbokki sauce.' },
          { name: 'Blood sausage', price: '₩8,000', rank: 3, pride: 'The usual second order.' },
          { name: 'Gimbap', price: '₩2,500', pride: 'Per roll. The solo-lunch combination.' },
        ],
        visit: [
          { label: 'Address', value: '11 Jungang Market-gil, Jayu Market B1, Wonju, Gangwon' },
          { label: 'Phone', value: '033-743-5822' },
          { label: 'Hours', value: 'Not officially listed — reviews say 11:00–19:30' },
          { label: 'Closed', value: 'Unconfirmed — reviews mention 1st and 3rd Sundays' },
        ],
        tips: [
          'When the tteokbokki runs out, that is the day. One review found it running low by 5pm — go early.',
          'Opening hours are not officially confirmed anywhere. Call ahead if it is a long trip.',
          'It is in the basement — you have to go down inside the market.',
        ],
        news: [
          {
            date: '2026-08-11',
            text: 'DiningCode lists the opening hours as “needs confirmation”. Reviews say 11:00–19:30, closed 1st and 3rd Sundays, but this is not an official listing.',
            source: { label: 'DiningCode', url: 'https://www.diningcode.com/profile.php?rid=qSeAPfgfMxtH' },
          },
        ],
      },
    },
  },
  {
    slug: 'myeongrang-makguksu-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '막국수',
    // ⚠️개업연도는 공개 자료에 없다. 다이닝코드가 '노포'로 분류하지만 연도 근거가 없어 비워 둔다
    //   (칩은 `ShopPage`/`ShopsIndex` 가 값이 있을 때만 그린다). 확인되면 채울 것.
    since: '',
    verified: '2026-08-10',
    cover: '/blog-assets/myeongrang-makguksu-wonju/img_00.png',
    images: [
      '/blog-assets/myeongrang-makguksu-wonju/img_01.png',
      '/blog-assets/myeongrang-makguksu-wonju/img_02.png',
    ],
    tel: '033-742-6805',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%EB%AA%85%EB%9E%91%EB%A7%89%EA%B5%AD%EC%88%98',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=uGBszVJqbmBH' },
      { label: '뽈레', url: 'https://polle.com/place/1Jkztf/%EB%AA%85%EB%9E%91%20%EB%A7%89%EA%B5%AD%EC%88%98' },
      { label: '식달 — 생활의 달인 아카이브', url: 'http://www.sikdal.com/bbs/board.php?bo_table=sd&wr_id=111' },
      { label: '카카오맵', url: 'https://m.map.kakao.com/actions/searchView?q=%EB%AA%85%EB%9E%91%EB%A7%89%EA%B5%AD%EC%88%98%20%EC%9B%90%EC%A3%BC' },
    ],
    copy: {
      ko: {
        name: '명랑막국수',
        tagline: '옛 원주역 옆 학성동, 막국수와 편육 한 접시로 버틴 골목집',
        story: [
          '원주역은 2021년에 무실동으로 옮겨갔습니다. 기차가 끊긴 뒤 학성동 일대는 조용해졌지만, 옛 역사 바로 옆 골목에는 그 전부터 있던 가게들이 남아 있습니다. 명랑막국수도 그중 하나입니다.',
          '메뉴판은 막국수와 편육을 중심으로 백숙·만두국까지 이어집니다. 다이닝코드는 이 집을 노포로, 그리고 지역 주민이 찾는 집으로 분류합니다. 관광 동선이 아니라 동네 사람의 동선 위에 있는 가게라는 뜻입니다.',
          '〈생활의 달인〉의 은둔식달 코너와 〈최자로드〉에 소개된 곳으로 기재되어 있습니다. 카카오맵 평점은 72건 기준 4.5, 다이닝코드는 4.4입니다.',
        ],
        menu: [
          {
            name: '막국수',
            price: '9,000원',
            rank: 1,
            pride:
              '이 집의 기준점입니다. 다이닝코드 방문 후기는 면발의 쫄깃함과 함께 나오는 동치미를 같이 꼽습니다. 막국수는 육수와 면의 온도가 전부라 처음이라면 비빔보다 이쪽을 먼저 드셔 보시는 편이 가게를 판단하기 쉽습니다.',
          },
          {
            name: '편육',
            price: '중 20,000~23,000원 · 대 25,000~28,000원',
            rank: 2,
            pride:
              '가게를 막국수집이 아니라 막국수·편육집으로 부르게 만든 메뉴입니다. 후기에서 반복해서 나오는 표현이 잡내가 없다는 것입니다. 다만 가격은 출처마다 달라 아래 가격 항목을 확인해 주세요.',
          },
          {
            name: '비빔막국수',
            price: '10,000원',
            rank: 3,
            pride: '물막국수와 1,000원 차이입니다. 둘을 함께 시켜 나눠 먹는 후기가 많습니다.',
          },
          { name: '만두국', price: '10,000원', pride: '면이 부담스러운 계절이나 아이 동반일 때의 선택지입니다.' },
          { name: '소고기불백', price: '14,000원', pride: '막국수만으로 식사가 안 되는 사람을 위한 밥 메뉴입니다.' },
          {
            name: '닭백숙 · 토종닭백숙 · 오리백숙',
            price: '30,000 / 45,000 / 50,000원',
            pride:
              '여러 명이 앉아 오래 먹는 자리를 위한 메뉴입니다. 토종닭도리탕 50,000원, 오리도리탕 55,000원도 있습니다. 조리에 시간이 걸리는 종류라 미리 전화로 주문해 두는 편이 낫습니다.',
          },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 원일로 180-1 (학성동 311-18)' },
          { label: '전화', value: '033-742-6805' },
          { label: '영업', value: '11:00~19:30' },
          { label: '휴무', value: '공개 자료에서 확인되지 않음 — 전화 확인 권장' },
          { label: '위치', value: '옛 원주역(학성동) 바로 인근' },
        ],
        tips: [
          '★주차 정보가 엇갈립니다. 다이닝코드 편의시설 태그는 무료주차와 주차불가가 함께 달려 있고, 방문 후기에는 주차가 곤란하니 인근 골목이나 공영주차장을 이용하라는 내용이 있습니다. 차로 가신다면 공영주차장을 먼저 염두에 두세요.',
          '19시 30분에 닫습니다. 저녁 늦게 움직이면 헛걸음합니다.',
          '편육 가격이 자료마다 다릅니다. 중 20,000원과 23,000원, 대 25,000원과 28,000원이 각각 다른 출처에 적혀 있습니다. 편육을 시킬 계획이면 전화로 확인하고 가세요.',
          '휴무일이 어느 자료에도 없습니다. 먼 길이라면 전화 한 통이 확실합니다.',
          '내비게이션은 현 원주역(무실동)이 아니라 학성동 원일로로 잡아야 합니다. 두 곳은 완전히 다른 위치입니다.',
        ],
        news: [
          {
            date: '2026-08-10',
            text: '확인 시점 기준 영업시간은 11:00~19:30으로 기재되어 있습니다. 휴무일 항목은 비어 있어 방문 전 전화 확인을 권합니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=uGBszVJqbmBH' },
          },
          {
            date: '방영 시점 미상',
            text: '〈생활의 달인〉 은둔식달 코너와 〈최자로드〉에 소개된 곳으로 기재되어 있습니다. 방영 회차와 날짜는 확인하지 못했습니다.',
            source: { label: '식달', url: 'http://www.sikdal.com/bbs/board.php?bo_table=sd&wr_id=111' },
          },
        ],
      },
      en: {
        name: 'Myeongrang Makguksu',
        tagline: 'Cold buckwheat noodles and sliced pork, in the back lanes beside Wonju’s old station',
        story: [
          'Wonju Station moved to Musil-dong in 2021. The Hakseong-dong district around the old station went quiet after the trains stopped, but the shops that were there before are still there. This is one of them.',
          'The menu runs from makguksu (cold buckwheat noodles) and pyeonyuk (sliced boiled pork) through to whole-chicken and duck pots. DiningCode files it under “old-timer” and “where locals go” — it sits on a neighbourhood route, not a tourist one.',
          'It is recorded as having appeared on the Korean TV programmes “Life’s Master” and “Choija Road”. Kakao Map rates it 4.5 from 72 ratings; DiningCode 4.4.',
        ],
        menu: [
          { name: 'Makguksu (cold buckwheat noodles)', price: '₩9,000', rank: 1, pride: 'The baseline dish. Reviews single out the chew of the noodles and the dongchimi (radish water kimchi) served alongside.' },
          { name: 'Pyeonyuk (sliced boiled pork)', price: '₩20,000–23,000 (M) · ₩25,000–28,000 (L)', rank: 2, pride: 'The dish that makes this a noodle-and-pork house rather than just a noodle house. Sources disagree on the price — call ahead.' },
          { name: 'Bibim makguksu (spicy, sauced)', price: '₩10,000', rank: 3, pride: 'A thousand won more than the cold-broth version. Many parties order both and share.' },
          { name: 'Mandu-guk (dumpling soup)', price: '₩10,000', pride: 'The warm option.' },
          { name: 'Beef bulgogi with rice', price: '₩14,000', pride: 'For anyone who does not count noodles as a meal.' },
          { name: 'Chicken / free-range chicken / duck pot', price: '₩30,000 / ₩45,000 / ₩50,000', pride: 'Long-table food. These take time to cook — call ahead.' },
        ],
        visit: [
          { label: 'Address', value: '180-1 Wonil-ro, Hakseong-dong, Wonju, Gangwon' },
          { label: 'Phone', value: '033-742-6805' },
          { label: 'Hours', value: '11:00–19:30' },
          { label: 'Closed', value: 'Not stated in any public source — please call' },
          { label: 'Location', value: 'Beside the former Wonju Station' },
        ],
        tips: [
          'Parking information conflicts. One review says parking is difficult and recommends the nearby public car park. Plan for that if you drive.',
          'It closes at 19:30 — not an option for a late dinner.',
          'Pyeonyuk prices differ between sources. Call ahead if you plan to order it.',
          'Navigate to Hakseong-dong, not the current Wonju Station in Musil-dong. They are far apart.',
        ],
        news: [
          {
            date: '2026-08-10',
            text: 'Hours are listed as 11:00–19:30 as of this check. No closing day is listed anywhere, so call ahead.',
            source: { label: 'DiningCode', url: 'https://www.diningcode.com/profile.php?rid=uGBszVJqbmBH' },
          },
        ],
      },
    },
  },
  {
    slug: 'nambu-tongdak-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '통닭',
    since: '1977',
    verified: '2026-08-01',
    cover: '/blog-assets/nambu-tongdak-wonju/img_00.png',
    images: [
      '/blog-assets/nambu-tongdak-wonju/img_01.png',
      '/blog-assets/nambu-tongdak-wonju/img_02.png',
    ],
    tel: '033-762-7144',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%EB%82%A8%EB%B6%80%ED%86%B5%EB%8B%AD',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=lTPlc2EBTPAo' },
      { label: '식신', url: 'https://www.siksinhot.com/P/363841' },
      { label: '톱스타뉴스 — 6시 내고향 방영', url: 'https://www.topstarnews.net/news/articleView.html?idxno=15439985' },
    ],
    copy: {
      ko: {
        name: '남부통닭',
        tagline: '1977년부터 가마솥을 지킨 원주 3대 통닭집',
        story: [
          '원주에서 통닭 이야기를 꺼내면 반드시 나오는 이름입니다. 개운동의 남부통닭은 1977년에 문을 열어 3대째 같은 자리를 지키고 있고, 원주시가 오래된 가게에 주는 전통 지정도 받았습니다.',
          '문을 연 1977년은 한국에 프랜차이즈 치킨이라는 개념이 아직 없던 때입니다. 당시 통닭은 닭 한 마리를 통째로 기름에 넣어 튀겨 내는 음식이었고, 조각으로 나누고 소스를 바르는 지금의 치킨과는 다른 계보에 있었습니다.',
          '반세기 가까이 버틴 방식은 단순합니다 — 바꾸지 않는 것. 대형 무쇠 가마솥, 국내산 12호 닭, 그리고 후라이드·양념·간장 세 가지뿐인 메뉴입니다.',
        ],
        menu: [
          {
            name: '후라이드',
            price: '21,000원',
            rank: 1,
            pride:
              '이 집의 기준점입니다. 가마솥의 두꺼운 무쇠 벽은 닭을 넣는 순간에도 기름 온도가 덜 떨어지게 붙잡아 줍니다. 겉이 먼저 굳고 속은 수분을 안고 익어서, 흔히 말하는 겉바속촉이 소스 없이 나옵니다. 처음이라면 이것부터 드세요.',
          },
          {
            name: '양념통닭',
            price: '22,000원',
            rank: 2,
            pride:
              '튀김옷이 두껍지 않아 소스를 발라도 눅눅해지기까지 시간이 걸립니다. 옛날 통닭집 양념 특유의 맵기보다 단맛이 앞서는 계열이라 아이들과 나눠 먹기 좋습니다.',
          },
          {
            name: '간장통닭',
            price: '22,000원',
            rank: 3,
            pride:
              '짠맛으로 밀지 않고 마늘과 간장의 향으로 가는 쪽입니다. 후라이드의 고소함을 덮지 않아서, 튀김 자체를 맛보고 싶은데 소스도 원할 때 절충안이 됩니다.',
          },
          {
            name: '반반',
            price: '22,000~23,000원',
            pride:
              '12호 닭이라 반반으로 나눠도 각각의 양이 부족하지 않습니다. 두 번째 방문에 취향을 고를 때 쓰기 좋은 선택지입니다.',
          },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 치악로 1774 (개운동 397-3)' },
          { label: '전화', value: '033-762-7144' },
          { label: '영업', value: '화~일 14:00~22:00' },
          { label: '휴무', value: '매주 월요일' },
          { label: '이용', value: '포장·배달만 (홀 영업 없음)' },
        ],
        tips: [
          '홀 영업을 하지 않습니다. 앉아서 먹을 생각으로 가면 헛걸음합니다.',
          '오후 2시에 엽니다. 점심 시간대에 가면 문이 닫혀 있습니다.',
          '가마솥에 튀기는 방식이라 시간이 걸립니다. 주말 저녁은 미리 전화로 주문해 두고 시간 맞춰 찾아가는 편이 낫습니다.',
          '12호 닭이라 한 마리로 두세 명이 먹기 좋은 크기입니다.',
        ],
        news: [
          {
            date: '2023-12',
            text: 'KBS1 〈6시 내고향〉에 원주 개운동의 3대째 노포 통닭집으로 소개되었습니다.',
            source: { label: '톱스타뉴스', url: 'https://www.topstarnews.net/news/articleView.html?idxno=15439985' },
          },
          {
            date: '2026-08-01',
            text: '확인 시점 기준 홀 영업 없이 포장·배달만 운영합니다. 영업시간은 화~일 14:00~22:00, 월요일 휴무입니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=lTPlc2EBTPAo' },
          },
        ],
      },
      en: {
        name: 'Nambu Tongdak',
        tagline: 'A third-generation whole-chicken shop in Wonju, frying in a cast-iron cauldron since 1977',
        story: [
          'Ask about fried chicken in Wonju and this name comes up. Nambu Tongdak opened in 1977 in Gaeun-dong and is now run by the third generation in the same spot.',
          'In 1977 franchise chicken did not exist in Korea. Tongdak meant a whole bird dropped into oil — a different lineage from the sauced, portioned chicken of today.',
          'The method has not changed: a heavy cast-iron cauldron, large domestic birds, and exactly three items on the menu.',
        ],
        menu: [
          { name: 'Fried (plain)', price: '₩21,000', rank: 1, pride: 'The baseline. The cauldron’s thick iron wall keeps the oil from dropping when the bird goes in, so the crust sets before the inside dries out.' },
          { name: 'Yangnyeom (sweet-spicy)', price: '₩22,000', rank: 2, pride: 'The batter is thin enough that the glaze takes a while to soften it. Sweet-forward rather than hot.' },
          { name: 'Ganjang (soy-garlic)', price: '₩22,000', rank: 3, pride: 'Carried by garlic and soy aroma rather than salt, so it does not bury the fry itself.' },
          { name: 'Half and half', price: '₩22,000~23,000', pride: 'The birds are large, so splitting still leaves a proper portion of each.' },
        ],
        visit: [
          { label: 'Address', value: '1774 Chiak-ro, Wonju, Gangwon' },
          { label: 'Phone', value: '033-762-7144' },
          { label: 'Hours', value: 'Tue–Sun 14:00–22:00' },
          { label: 'Closed', value: 'Mondays' },
          { label: 'Service', value: 'Takeaway & delivery only' },
        ],
        tips: [
          'There is no dine-in. Takeaway and delivery only.',
          'Opens at 2pm — closed at lunchtime.',
          'Cauldron frying takes time; call ahead on weekend evenings.',
        ],
        news: [
          { date: '2023-12', text: 'Featured on KBS1 “6 O’Clock My Hometown” as a third-generation neighbourhood chicken shop.', source: { label: 'Topstarnews', url: 'https://www.topstarnews.net/news/articleView.html?idxno=15439985' } },
        ],
      },
    },
  },
];

/* ===== 헬퍼 ===== */
export function shopCopy(shop: ShopEntry, lang: Lang): ShopCopy {
  // 번역이 없는 언어는 영어 → 한국어 순으로 폴백한다(빈 페이지를 만들지 않기 위해).
  return shop.copy[lang] ?? shop.copy.en ?? shop.copy.ko;
}
export function shopsIndexUrl(lang: Lang): string {
  return localizeUrl('/shops/', lang);
}
export function shopUrl(slug: string, lang: Lang): string {
  return localizeUrl(`/shops/${slug}/`, lang);
}
export function telHref(tel: string): string {
  return `tel:${tel.replace(/[^0-9+]/g, '')}`;
}
export function newsIndexUrl(lang: Lang): string {
  return localizeUrl('/news/', lang);
}

/** 카드·상세에 쓰는 지역 표기. 예: '강원도 원주' */
export function shopLocation(shop: ShopEntry, lang: Lang): string {
  return `${regionLabel(shop.region, lang)} ${shop.city}`.trim();
}

/** 카드에 쓰는 업종 표기. 세부 표기가 있으면 그걸 우선한다(‘음식점’보다 ‘통닭’이 정보량이 크다). */
export function shopCategoryText(shop: ShopEntry, lang: Lang): string {
  if (lang === 'ko' && shop.categoryDetail) return shop.categoryDetail;
  return categoryLabel(shop.category, lang);
}

/** ⚠️**등록이 0인 지역·업종은 아예 내보내지 않는다.**
 *  업체가 1곳인데 '서울 0곳 / 경기도 0곳' 칸을 보여주면 빈 서랍을 자랑하는 꼴이고,
 *  사장님께 보여줄 때 제일 먼저 눈에 띄는 게 그 빈칸이 된다. 채워진 것만 보여준다. */
export function regionFacets(lang: Lang): { code: RegionCode; label: string; count: number }[] {
  return REGIONS.map((code) => ({
    code,
    label: regionLabel(code, lang),
    count: shops.filter((s) => s.region === code).length,
  })).filter((f) => f.count > 0);
}
export function categoryFacets(lang: Lang): { code: CategoryCode; label: string; count: number }[] {
  return CATEGORIES.map((code) => ({
    code,
    label: categoryLabel(code, lang),
    count: shops.filter((s) => s.category === code).length,
  })).filter((f) => f.count > 0);
}

/** 클라이언트 인스턴트 검색용 색인.
 *  ⚠️구글 CSE 는 **색인되지 않은 신규 업체를 못 찾는다.** 등록 직후부터 검색돼야 하므로
 *  자체 색인이 기본이고 구글은 보조다. 업체 수가 수백 곳이 되기 전까지 이 방식이 더 정확하다. */
export function searchIndex(lang: Lang) {
  return shops.map((shop) => {
    const c = shopCopy(shop, lang);
    const terms = [
      c.name,
      c.tagline,
      shopLocation(shop, lang),
      shop.city,
      regionLabel(shop.region, lang),
      categoryLabel(shop.category, lang),
      shop.categoryDetail ?? '',
      ...c.menu.map((m) => m.name),
    ];
    return {
      slug: shop.slug,
      region: shop.region,
      category: shop.category,
      q: terms.join(' ').toLowerCase(),
    };
  });
}

/** 등록 업체 전체의 소식을 최신순으로 합친다(가게 상세에 흩어져 있는 것을 한 줄기로).
 *  origin: 'press' = menewsoft 가 공개 자료에서 정리(출처 필수) */
export function allShopNews(lang: Lang) {
  const rows = shops.flatMap((shop) => {
    const c = shopCopy(shop, lang);
    return c.news.map((n) => ({
      shop,
      shopName: c.name,
      date: n.date,
      text: n.text,
      source: n.source,
      origin: 'press' as const,
    }));
  });
  return rows.sort((a, b) => (a.date < b.date ? 1 : -1));
}
