// 지역 가게 섹션: 가게 레지스트리 + 섹션 문자열.
// 새 가게는 shops 배열에 항목을 추가하면 목록/상세 페이지가 자동 생성된다(게임 섹션과 같은 구조).
//
// ⚠️★이 섹션은 **가게의 공식 홈페이지가 아니다.** menewsoft 가 직접 조사해서 쓰는 독립 소개
//   페이지다. 그래서 지켜야 할 규칙이 있다:
//   1) **가게 명의로 공지를 쓰지 않는다.** `news` 는 반드시 출처(source)를 달고, 가게가 한 말이
//      아니라 '어디에 이렇게 보도/기재되어 있다'로 적는다. 가게가 하지 않은 공지를 손님이 믿고
//      움직이면 손님도 가게도 실제 피해를 본다.
//   2) **건의·문의는 가게 전화로 직접 보낸다.** 정적 사이트라 백엔드가 없어서 게시판 글을 받아도
//      사장님께 전달할 방법이 없다. '접수되는 것처럼 보이는' 폼이 제일 나쁘다.
//   3) 가격·영업시간은 **확인 날짜(verified)** 를 함께 표기하고 '방문 전 확인'을 안내한다.
//   4) 사진은 남의 것을 가져오지 않는다. 직접 생성한 일러스트를 쓰고 그렇다고 명시한다.
import type { Lang } from './ui';
import { localizeUrl } from './utils';

/* ===== 섹션 공통 문자열 ===== */
export const shopsUi: Record<Lang, Record<string, string>> = {
  ko: {
    kicker: '지역 가게',
    pageTitle: '지역 가게',
    metaDescription:
      '오래 버틴 동네 가게를 직접 찾아 정리합니다. 메뉴와 가격, 영업시간, 그리고 가기 전에 알아야 할 것들.',
    intro:
      '프랜차이즈가 전국을 덮은 뒤에도 같은 자리에서 같은 방식으로 버티는 가게들이 있습니다. 그런 가게를 하나씩 정리합니다 — 메뉴와 가격, 영업시간, 그리고 헛걸음하지 않도록 미리 알아야 할 것들까지.',
    viewShop: '가게 보기 →',
    backToList: '← 지역 가게 목록',
    sinceLabel: '개업',
    newsTitle: '최근 소식',
    menuTitle: '메뉴',
    prideTitle: '이 메뉴의 강점',
    visitTitle: '가기 전에',
    contactTitle: '건의·문의',
    disclaimerTitle: '이 페이지에 대하여',
    callNow: '전화하기',
    verifiedPrefix: '확인 시점',
    priceNote: '가격·영업시간은 바뀔 수 있습니다. 방문 전 전화로 확인하세요.',
    illustNote: '이 페이지의 그림은 분위기를 전하기 위해 직접 생성한 AI 일러스트입니다. 실제 가게의 음식·매장 사진이 아닙니다.',
    sourceLabel: '출처',
  },
  en: {
    kicker: 'LOCAL SHOPS',
    pageTitle: 'Local Shops',
    metaDescription:
      'Long-running neighbourhood shops in Korea, researched and written up first-hand: menus, prices, hours and what to know before you go.',
    intro:
      'Some shops keep doing the same thing in the same place long after the franchises took over. We write them up one by one — menu, prices, hours, and the things you need to know so you do not make a wasted trip.',
    viewShop: 'View shop →',
    backToList: '← All shops',
    sinceLabel: 'Since',
    newsTitle: 'Latest',
    menuTitle: 'Menu',
    prideTitle: 'Why this one',
    visitTitle: 'Before you go',
    contactTitle: 'Feedback',
    disclaimerTitle: 'About this page',
    callNow: 'Call',
    verifiedPrefix: 'Verified',
    priceNote: 'Prices and hours change. Please call ahead.',
    illustNote: 'Illustrations on this page were generated by us to set the mood. They are not photographs of the actual shop or its food.',
    sourceLabel: 'Source',
  },
  ja: {
    kicker: 'ローカル店',
    pageTitle: 'ローカル店',
    metaDescription: '長く続く韓国の街の名店を自分たちで調べてまとめます。メニュー、価格、営業時間、行く前に知っておくこと。',
    intro: 'チェーン店が広がった後も、同じ場所で同じやり方を守る店があります。そんな店を一軒ずつ紹介します。',
    viewShop: '店を見る →', backToList: '← 一覧へ', sinceLabel: '創業', newsTitle: '最新情報',
    menuTitle: 'メニュー', prideTitle: 'この一品の強み', visitTitle: '行く前に', contactTitle: 'ご意見',
    disclaimerTitle: 'このページについて', callNow: '電話する', verifiedPrefix: '確認時点',
    priceNote: '価格・営業時間は変わることがあります。訪問前に電話でご確認ください。',
    illustNote: 'このページの画像は雰囲気を伝えるために生成したAIイラストです。実際の店舗・料理の写真ではありません。',
    sourceLabel: '出典',
  },
  es: {
    kicker: 'LOCALES DE BARRIO',
    pageTitle: 'Locales de barrio',
    metaDescription: 'Locales coreanos de toda la vida, investigados de primera mano: carta, precios, horarios y lo que hay que saber antes de ir.',
    intro: 'Hay locales que siguen haciendo lo mismo en el mismo sitio mucho después de que llegaran las cadenas. Los vamos contando uno a uno.',
    viewShop: 'Ver local →', backToList: '← Todos los locales', sinceLabel: 'Desde', newsTitle: 'Novedades',
    menuTitle: 'Carta', prideTitle: 'Por qué este', visitTitle: 'Antes de ir', contactTitle: 'Sugerencias',
    disclaimerTitle: 'Sobre esta página', callNow: 'Llamar', verifiedPrefix: 'Verificado',
    priceNote: 'Los precios y horarios cambian. Llama antes de ir.',
    illustNote: 'Las ilustraciones de esta página las generamos nosotros. No son fotos del local ni de su comida.',
    sourceLabel: 'Fuente',
  },
  zh: {
    kicker: '本地老店',
    pageTitle: '本地老店',
    metaDescription: '亲自走访整理的韩国老字号小店：菜单、价格、营业时间，以及出发前该知道的事。',
    intro: '连锁店铺开遍全国之后，仍有一些店在同一个地方用同样的做法坚持着。我们一家一家记录下来。',
    viewShop: '查看店铺 →', backToList: '← 返回列表', sinceLabel: '创立', newsTitle: '最新动态',
    menuTitle: '菜单', prideTitle: '这道菜的看点', visitTitle: '出发前', contactTitle: '意见反馈',
    disclaimerTitle: '关于本页', callNow: '拨打电话', verifiedPrefix: '核实时间',
    priceNote: '价格与营业时间可能变动，前往前请先致电确认。',
    illustNote: '本页插图为我们生成的 AI 插画，并非该店实际菜品或门店照片。',
    sourceLabel: '来源',
  },
};

/* ===== 지역·업종 분류 =====
   ⚠️분류 코드는 **자유 문자열이 아니라 코드**다. 디렉토리 필터·검색 인덱스가 이 코드로 묶이기
   때문에 '강원 원주'/'강원도 원주시'처럼 표기가 흔들리면 같은 지역이 두 칸으로 쪼개진다.
   시·군(city)만 자유 문자열로 둔다. */
export const REGIONS = ['seoul', 'gyeonggi', 'gangwon'] as const;
export type RegionCode = (typeof REGIONS)[number];

export const CATEGORIES = ['food', 'cafe', 'beauty', 'academy', 'repair', 'etc'] as const;
export type CategoryCode = (typeof CATEGORIES)[number];

export const regionLabels: Record<RegionCode, Partial<Record<Lang, string>> & { ko: string }> = {
  seoul: { ko: '서울', en: 'Seoul', ja: 'ソウル', es: 'Seúl', zh: '首尔' },
  gyeonggi: { ko: '경기도', en: 'Gyeonggi', ja: '京畿道', es: 'Gyeonggi', zh: '京畿道' },
  gangwon: { ko: '강원도', en: 'Gangwon', ja: '江原道', es: 'Gangwon', zh: '江原道' },
};

export const categoryLabels: Record<CategoryCode, Partial<Record<Lang, string>> & { ko: string }> = {
  food: { ko: '음식점', en: 'Restaurants', ja: '飲食店', es: 'Restaurantes', zh: '餐厅' },
  cafe: { ko: '카페·베이커리', en: 'Cafés & bakeries', ja: 'カフェ', es: 'Cafeterías', zh: '咖啡·烘焙' },
  beauty: { ko: '미용·이용', en: 'Hair & beauty', ja: '美容', es: 'Peluquería', zh: '美容' },
  academy: { ko: '학원·교습', en: 'Academies', ja: '学習塾', es: 'Academias', zh: '培训' },
  repair: { ko: '수리·정비', en: 'Repair', ja: '修理', es: 'Reparación', zh: '维修' },
  etc: { ko: '그 밖의 업종', en: 'Other', ja: 'その他', es: 'Otros', zh: '其他' },
};

export function regionLabel(code: RegionCode, lang: Lang): string {
  return regionLabels[code][lang] ?? regionLabels[code].ko;
}
export function categoryLabel(code: CategoryCode, lang: Lang): string {
  return categoryLabels[code][lang] ?? categoryLabels[code].ko;
}

/* ===== 데이터 모델 ===== */
export interface MenuItem {
  name: string;
  price: string;
  /** 이 메뉴를 왜 시키는가 — 조리법·재료·식감 근거로. 과장 금지. */
  pride: string;
  /** 처음 온 사람에게 추천하는 순서(1이 가장 먼저) */
  rank?: number;
}
export interface NewsItem {
  date: string;
  text: string;
  /** ⚠️**필수**(타입 강제) — 가게 명의 공지가 아니라 '어디에 이렇게 나와 있다'임을 밝힌다.
   *  출처 없는 소식은 우리가 지어낸 말이 되고, 손님이 그걸 믿고 헛걸음하면 가게가 피해를 본다.
   *  출처를 못 찾으면 **쓰지 않는다**. 그래서 optional 이 아니라 required 다(빠지면 빌드 실패). */
  source: { label: string; url: string };
}
export interface ShopCopy {
  name: string;
  tagline: string;
  /** 히어로 아래 본문(문단 배열) */
  story: string[];
  menu: MenuItem[];
  /** 방문 정보(라벨/값) */
  visit: { label: string; value: string }[];
  /** 가기 전 주의사항 */
  tips: string[];
  news: NewsItem[];
}
export interface ShopEntry {
  slug: string;
  /** 광역 지역 코드(필터 단위) */
  region: RegionCode;
  /** 시·군 — 표시·검색용. 예: '원주' */
  city: string;
  /** 업종 코드(필터 단위) */
  category: CategoryCode;
  /** 업종 세부 표기. 예: '통닭' — 필터에는 안 쓰고 카드·검색어에만 쓴다 */
  categoryDetail?: string;
  since: string;
  /** 확인 날짜 — 가격·영업시간이 언제 기준인지 */
  verified: string;
  cover: string;
  images: string[];
  tel: string;
  mapUrl: string;
  sources: { label: string; url: string }[];
  copy: Partial<Record<Lang, ShopCopy>> & { ko: ShopCopy };
}

export const shops: ShopEntry[] = [
  {
    slug: 'nambu-tongdak-wonju',
    region: 'gangwon',
    city: '원주',
    category: 'food',
    categoryDetail: '통닭',
    since: '1977',
    verified: '2026-08-01',
    cover: '/blog-assets/nambu-tongdak-wonju/img_00.png',
    images: [
      '/blog-assets/nambu-tongdak-wonju/img_01.png',
      '/blog-assets/nambu-tongdak-wonju/img_02.png',
    ],
    tel: '033-762-7144',
    mapUrl: 'https://map.naver.com/p/search/%EC%9B%90%EC%A3%BC%20%EB%82%A8%EB%B6%80%ED%86%B5%EB%8B%AD',
    sources: [
      { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=lTPlc2EBTPAo' },
      { label: '식신', url: 'https://www.siksinhot.com/P/363841' },
      { label: '톱스타뉴스 — 6시 내고향 방영', url: 'https://www.topstarnews.net/news/articleView.html?idxno=15439985' },
    ],
    copy: {
      ko: {
        name: '남부통닭',
        tagline: '1977년부터 가마솥을 지킨 원주 3대 통닭집',
        story: [
          '원주에서 통닭 이야기를 꺼내면 반드시 나오는 이름입니다. 개운동의 남부통닭은 1977년에 문을 열어 3대째 같은 자리를 지키고 있고, 원주시가 오래된 가게에 주는 전통 지정도 받았습니다.',
          '문을 연 1977년은 한국에 프랜차이즈 치킨이라는 개념이 아직 없던 때입니다. 당시 통닭은 닭 한 마리를 통째로 기름에 넣어 튀겨 내는 음식이었고, 조각으로 나누고 소스를 바르는 지금의 치킨과는 다른 계보에 있었습니다.',
          '반세기 가까이 버틴 방식은 단순합니다 — 바꾸지 않는 것. 대형 무쇠 가마솥, 국내산 12호 닭, 그리고 후라이드·양념·간장 세 가지뿐인 메뉴입니다.',
        ],
        menu: [
          {
            name: '후라이드',
            price: '21,000원',
            rank: 1,
            pride:
              '이 집의 기준점입니다. 가마솥의 두꺼운 무쇠 벽은 닭을 넣는 순간에도 기름 온도가 덜 떨어지게 붙잡아 줍니다. 겉이 먼저 굳고 속은 수분을 안고 익어서, 흔히 말하는 겉바속촉이 소스 없이 나옵니다. 처음이라면 이것부터 드세요.',
          },
          {
            name: '양념통닭',
            price: '22,000원',
            rank: 2,
            pride:
              '튀김옷이 두껍지 않아 소스를 발라도 눅눅해지기까지 시간이 걸립니다. 옛날 통닭집 양념 특유의 맵기보다 단맛이 앞서는 계열이라 아이들과 나눠 먹기 좋습니다.',
          },
          {
            name: '간장통닭',
            price: '22,000원',
            rank: 3,
            pride:
              '짠맛으로 밀지 않고 마늘과 간장의 향으로 가는 쪽입니다. 후라이드의 고소함을 덮지 않아서, 튀김 자체를 맛보고 싶은데 소스도 원할 때 절충안이 됩니다.',
          },
          {
            name: '반반',
            price: '22,000~23,000원',
            pride:
              '12호 닭이라 반반으로 나눠도 각각의 양이 부족하지 않습니다. 두 번째 방문에 취향을 고를 때 쓰기 좋은 선택지입니다.',
          },
        ],
        visit: [
          { label: '주소', value: '강원 원주시 치악로 1774 (개운동 397-3)' },
          { label: '전화', value: '033-762-7144' },
          { label: '영업', value: '화~일 14:00~22:00' },
          { label: '휴무', value: '매주 월요일' },
          { label: '이용', value: '포장·배달만 (홀 영업 없음)' },
        ],
        tips: [
          '홀 영업을 하지 않습니다. 앉아서 먹을 생각으로 가면 헛걸음합니다.',
          '오후 2시에 엽니다. 점심 시간대에 가면 문이 닫혀 있습니다.',
          '가마솥에 튀기는 방식이라 시간이 걸립니다. 주말 저녁은 미리 전화로 주문해 두고 시간 맞춰 찾아가는 편이 낫습니다.',
          '12호 닭이라 한 마리로 두세 명이 먹기 좋은 크기입니다.',
        ],
        news: [
          {
            date: '2023-12',
            text: 'KBS1 〈6시 내고향〉에 원주 개운동의 3대째 노포 통닭집으로 소개되었습니다.',
            source: { label: '톱스타뉴스', url: 'https://www.topstarnews.net/news/articleView.html?idxno=15439985' },
          },
          {
            date: '2026-08-01',
            text: '확인 시점 기준 홀 영업 없이 포장·배달만 운영합니다. 영업시간은 화~일 14:00~22:00, 월요일 휴무입니다.',
            source: { label: '다이닝코드', url: 'https://www.diningcode.com/profile.php?rid=lTPlc2EBTPAo' },
          },
        ],
      },
      en: {
        name: 'Nambu Tongdak',
        tagline: 'A third-generation whole-chicken shop in Wonju, frying in a cast-iron cauldron since 1977',
        story: [
          'Ask about fried chicken in Wonju and this name comes up. Nambu Tongdak opened in 1977 in Gaeun-dong and is now run by the third generation in the same spot.',
          'In 1977 franchise chicken did not exist in Korea. Tongdak meant a whole bird dropped into oil — a different lineage from the sauced, portioned chicken of today.',
          'The method has not changed: a heavy cast-iron cauldron, large domestic birds, and exactly three items on the menu.',
        ],
        menu: [
          { name: 'Fried (plain)', price: '₩21,000', rank: 1, pride: 'The baseline. The cauldron’s thick iron wall keeps the oil from dropping when the bird goes in, so the crust sets before the inside dries out.' },
          { name: 'Yangnyeom (sweet-spicy)', price: '₩22,000', rank: 2, pride: 'The batter is thin enough that the glaze takes a while to soften it. Sweet-forward rather than hot.' },
          { name: 'Ganjang (soy-garlic)', price: '₩22,000', rank: 3, pride: 'Carried by garlic and soy aroma rather than salt, so it does not bury the fry itself.' },
          { name: 'Half and half', price: '₩22,000~23,000', pride: 'The birds are large, so splitting still leaves a proper portion of each.' },
        ],
        visit: [
          { label: 'Address', value: '1774 Chiak-ro, Wonju, Gangwon' },
          { label: 'Phone', value: '033-762-7144' },
          { label: 'Hours', value: 'Tue–Sun 14:00–22:00' },
          { label: 'Closed', value: 'Mondays' },
          { label: 'Service', value: 'Takeaway & delivery only' },
        ],
        tips: [
          'There is no dine-in. Takeaway and delivery only.',
          'Opens at 2pm — closed at lunchtime.',
          'Cauldron frying takes time; call ahead on weekend evenings.',
        ],
        news: [
          { date: '2023-12', text: 'Featured on KBS1 “6 O’Clock My Hometown” as a third-generation neighbourhood chicken shop.', source: { label: 'Topstarnews', url: 'https://www.topstarnews.net/news/articleView.html?idxno=15439985' } },
        ],
      },
    },
  },
];

/* ===== 헬퍼 ===== */
export function shopCopy(shop: ShopEntry, lang: Lang): ShopCopy {
  // 번역이 없는 언어는 영어 → 한국어 순으로 폴백한다(빈 페이지를 만들지 않기 위해).
  return shop.copy[lang] ?? shop.copy.en ?? shop.copy.ko;
}
export function shopsIndexUrl(lang: Lang): string {
  return localizeUrl('/shops/', lang);
}
export function shopUrl(slug: string, lang: Lang): string {
  return localizeUrl(`/shops/${slug}/`, lang);
}
export function telHref(tel: string): string {
  return `tel:${tel.replace(/[^0-9+]/g, '')}`;
}
export function newsIndexUrl(lang: Lang): string {
  return localizeUrl('/news/', lang);
}

/** 카드·상세에 쓰는 지역 표기. 예: '강원도 원주' */
export function shopLocation(shop: ShopEntry, lang: Lang): string {
  return `${regionLabel(shop.region, lang)} ${shop.city}`.trim();
}

/** 카드에 쓰는 업종 표기. 세부 표기가 있으면 그걸 우선한다(‘음식점’보다 ‘통닭’이 정보량이 크다). */
export function shopCategoryText(shop: ShopEntry, lang: Lang): string {
  if (lang === 'ko' && shop.categoryDetail) return shop.categoryDetail;
  return categoryLabel(shop.category, lang);
}

/** ⚠️**등록이 0인 지역·업종은 아예 내보내지 않는다.**
 *  업체가 1곳인데 '서울 0곳 / 경기도 0곳' 칸을 보여주면 빈 서랍을 자랑하는 꼴이고,
 *  사장님께 보여줄 때 제일 먼저 눈에 띄는 게 그 빈칸이 된다. 채워진 것만 보여준다. */
export function regionFacets(lang: Lang): { code: RegionCode; label: string; count: number }[] {
  return REGIONS.map((code) => ({
    code,
    label: regionLabel(code, lang),
    count: shops.filter((s) => s.region === code).length,
  })).filter((f) => f.count > 0);
}
export function categoryFacets(lang: Lang): { code: CategoryCode; label: string; count: number }[] {
  return CATEGORIES.map((code) => ({
    code,
    label: categoryLabel(code, lang),
    count: shops.filter((s) => s.category === code).length,
  })).filter((f) => f.count > 0);
}

/** 클라이언트 인스턴트 검색용 색인.
 *  ⚠️구글 CSE 는 **색인되지 않은 신규 업체를 못 찾는다.** 등록 직후부터 검색돼야 하므로
 *  자체 색인이 기본이고 구글은 보조다. 업체 수가 수백 곳이 되기 전까지 이 방식이 더 정확하다. */
export function searchIndex(lang: Lang) {
  return shops.map((shop) => {
    const c = shopCopy(shop, lang);
    const terms = [
      c.name,
      c.tagline,
      shopLocation(shop, lang),
      shop.city,
      regionLabel(shop.region, lang),
      categoryLabel(shop.category, lang),
      shop.categoryDetail ?? '',
      ...c.menu.map((m) => m.name),
    ];
    return {
      slug: shop.slug,
      region: shop.region,
      category: shop.category,
      q: terms.join(' ').toLowerCase(),
    };
  });
}

/** 등록 업체 전체의 소식을 최신순으로 합친다(가게 상세에 흩어져 있는 것을 한 줄기로).
 *  origin: 'press' = menewsoft 가 공개 자료에서 정리(출처 필수) */
export function allShopNews(lang: Lang) {
  const rows = shops.flatMap((shop) => {
    const c = shopCopy(shop, lang);
    return c.news.map((n) => ({
      shop,
      shopName: c.name,
      date: n.date,
      text: n.text,
      source: n.source,
      origin: 'press' as const,
    }));
  });
  return rows.sort((a, b) => (a.date < b.date ? 1 : -1));
}
