/* 삼한통일전 — 사건 만화 대본.
 *
 * 사건(engine.js EVENTS)마다 칸을 여러 개 둔다. 칸 하나는
 *   s    배경 장면(scenes.js)
 *   cast 등장인물 — 무장 id, '@' 로 시작하면 아래 EXTRAS(무장 명단에 없는 사람),
 *        '{lord}' 는 지금 그 세력의 군주
 *   nar  나레이션 [한국어, 영어] — 칸 위 해설 상자에 찍히고 소리로도 읽는다
 *   say  말풍선 [[말하는 이, 한국어, 영어], ...]
 *   fx   효과 글자 [한국어, 영어]
 *   snd  효과음 이름(sound.js)
 * 글 안의 {fac}·{lord}·{castle}·{win} 은 화면에서 바꿔 끼운다.
 *
 * ★사료 사건은 사서에 적힌 줄거리를 벗어나지 않는다. 사서끼리 어긋나거나(석우로 249/253)
 *   학설이 갈리는 곳(247년 평양성의 위치)은 칸 안에서 그렇다고 말한다.
 * ★가상 사건(kind: fic)은 전부 창작이며 화면에 '가상 이야기' 표시가 붙는다.
 */
(function () {
  'use strict';

  const EXTRAS = {
    '@interp':     { ko: '역관', en: 'Interpreter', sex: '남' },
    '@weigen':     { ko: '위의 장수', en: 'Wei commander', sex: '남' },
    '@okjeo':      { ko: '옥저의 짐꾼', en: 'Okjeo porter', sex: '남' },
    '@official':   { ko: '곳간지기', en: 'Granary keeper', sex: '남' },
    '@elder':      { ko: '마을 어른', en: 'Village elder', sex: '남' },
    '@wa_envoy':   { ko: '왜의 사신', en: 'Wa envoy', sex: '남' },
    '@zhangzheng': { ko: '장정', en: 'Zhang Zheng', sex: '남' },
    '@silla_envoy':{ ko: '사로의 사신', en: 'Envoy of Saro', sex: '남' },
    '@galnago':    { ko: '갈나고', en: 'Galnago', sex: '남' },
    '@wa_general': { ko: '우도주군', en: 'Udojugun', sex: '남' },
    '@gwanna':     { ko: '관나부인', en: 'Lady Gwanna', sex: '여' },
    '@queenyeon':  { ko: '왕후 연씨', en: 'Queen Yeon', sex: '여' },
    '@ikjong':     { ko: '익종', en: 'Ikjong', sex: '남' },
    '@weijihai':   { ko: '위지해', en: 'Yuchi Kai', sex: '남' },
    '@corrupt':    { ko: '탐욕스러운 관리', en: 'Greedy official', sex: '남' },
    '@simayan':    { ko: '사마염', en: 'Sima Yan', sex: '남' },
    '@lelang_off': { ko: '낙랑의 군관', en: 'Lelang officer', sex: '남' },
    '@bandit':     { ko: '도적 두목', en: 'Bandit chief', sex: '남' },
    '@farmer':     { ko: '농부', en: 'Farmer', sex: '남' },
    '@apprentice': { ko: '장정', en: 'Young man', sex: '남' },
    '@judge':      { ko: '겨루기 심판', en: 'Contest judge', sex: '남' },
    '@sick':       { ko: '앓는 사람', en: 'Sick man', sex: '남' },
    '@shaman':     { ko: '무당', en: 'Shaman', sex: '여' },
    '@pirate':     { ko: '해적 두목', en: 'Pirate captain', sex: '남' },
    '@merchant':   { ko: '낙랑 상인', en: 'Lelang merchant', sex: '남' },
    '@hunter':     { ko: '사냥꾼', en: 'Hunter', sex: '남' },
  };

  const STORY = {
    // ────────────────────────────── 여는 이야기 · 맺는 이야기
    prologue: [
      { s: 'map', nar: ['서기 246년. 부여의 벌판에서 규슈의 바다까지, 열일곱 나라가 한 하늘 아래 칼을 갈고 있었다.',
                        'AD 246. From the plains of Buyeo to the seas of Kyushu, seventeen powers were sharpening their blades under one sky.'] },
      { s: 'fortress', cast: ['guangui'],
        nar: ['서쪽에서는 위(魏)가 낙랑과 대방을 쥐고 동쪽을 노려보았다.',
              'In the west, Wei held Lelang and Daifang and glared eastward.'],
        say: [['guangui', '고구려의 왕을 끝까지 쫓아라. 환도성을 무너뜨려라.', 'Hunt the king of Goguryeo to the end. Bring Hwando down.']] },
      { s: 'village', cast: ['jinwang', 'goi'],
        nar: ['남쪽 마한 쉰네 나라 사이에서는 백제가, 진한에서는 사로가, 변한에서는 구야가 조용히 힘을 기르고 있었다.',
              'In the south, among the fifty-four states of Mahan, Baekje was quietly gathering strength — as were Saro in Jinhan and Guya in Byeonhan.'],
        say: [['goi', '큰 나라들이 싸우는 틈이 곧 우리의 기회다.', 'When the great powers fight, the gap between them is our chance.']] },
      { s: 'palace', cast: ['{lord}'],
        nar: ['그리고 지금, {fac}의 운명이 그대의 손에 놓였다.', 'And now the fate of {fac} rests in your hands.'],
        say: [['{lord}', '한 달이 한 걸음이다. 흩어진 삼한을 하나로 묶으리라.', 'Each month is one step. We will bind the scattered Han into one.']] },
    ],
    ending_win: [
      { s: 'ritual', cast: ['{lord}'],
        nar: ['긴 싸움 끝에, 흩어졌던 삼한의 깃발이 하나로 모였다.', 'After long years of war, the scattered banners of the Three Han were gathered into one.'],
        say: [['{lord}', '오늘부터 이 땅의 백성은 한 하늘을 이고 산다.', 'From this day the people of this land live under one sky.']] },
      { s: 'field', nar: ['창을 녹여 보습을 만들고, 성문 앞 저자에는 다시 사람이 붐볐다.',
                          'Spears were melted into ploughshares, and the markets before the gates filled with people again.'] },
      { s: 'night', nar: ['사람들은 오래도록 {fac}의 이름을 기억할 것이다.', 'People would remember the name of {fac} for a long time to come.'] },
    ],
    ending_lose: [
      { s: 'fire', cast: ['{lord}'],
        nar: ['{win}의 깃발이 마지막 성 위로 올랐다.', 'The banner of {win} rose over the last fortress.'],
        say: [['{lord}', '여기까지인가… 그러나 뜻은 칼보다 오래 산다.', 'So this is the end… yet a purpose outlives the sword.']] },
      { s: 'village', nar: ['{fac}의 이야기는 끝났으나, 흩어진 사람들은 저마다의 고을에서 다시 씨를 뿌렸다.',
                            'The tale of {fac} was over, but its scattered people sowed seed again in their own villages.'] },
      { s: 'night', nar: ['다른 판에서, 다른 길로 다시 해 보시겠습니까?', 'Will you try again — another power, another road?'] },
    ],

    // ────────────────────────────── 사료 사건 (원래 있던 7개)
    girinyeong: [
      { s: 'court', cast: ['orim', '@interp'],
        nar: ['낙랑의 부종사 오림이 진한 여덟 나라를 떼어 낙랑에 붙이려 했다.',
              'Wu Lin, an aide of Lelang, schemed to split eight states from Jinhan and attach them to Lelang.'],
        say: [['orim', '진한의 여덟 나라는 이제부터 낙랑이 거느린다.', 'From today, eight states of Jinhan answer to Lelang.']] },
      { s: 'court', cast: ['@interp', 'jinwang'],
        nar: ['그런데 통역이 말을 잘못 옮겼다.', 'But the interpreter got the words wrong.'],
        say: [['@interp', '…위가 한(韓)을 통째로 삼키겠다 합니다.', '…Wei says it will swallow all of Han.'],
              ['jinwang', '무어라? 우리를 종으로 보는가!', 'What? They take us for slaves!']] },
      { s: 'battle', cast: ['jinwang'], fx: ['와아!', 'RAAAH!'], snd: 'warcry',
        nar: ['격분한 한의 신지들이 군사를 일으켜 대방군의 기리영을 들이쳤다.',
              'Enraged, the chiefs of Han raised their men and stormed Girinyeong, a fort of Daifang.'],
        say: [['jinwang', '기리영을 불태워라!', 'Burn Girinyeong!']] },
      { s: 'fire', cast: ['gungjun'],
        nar: ['대방태수 궁준이 이 싸움에서 전사했다. 위의 보복도 곧 뒤따를 것이었다.',
              'Gong Zun, Grand Administrator of Daifang, fell in this fight. Wei\'s revenge would not be long in coming.'],
        say: [['gungjun', '성을… 지켜라…', 'Hold… the fort…']] },
    ],
    baekje_nakrang: [
      { s: 'palace', cast: ['goi', 'jinchung'],
        nar: ['위가 고구려로 군사를 돌린 틈이었다.', 'Wei had turned its armies on Goguryeo.'],
        say: [['goi', '좌장 진충, 낙랑의 변경이 비었다.', 'Commander Jinchung, the Lelang border lies empty.'],
              ['jinchung', '명을 받들겠습니다.', 'I obey.']] },
      { s: 'village', cast: ['jinchung'], fx: ['쾅!', 'CRASH'],
        nar: ['진충이 낙랑 변경을 습격해 주민을 사로잡아 돌아왔다.', 'Jinchung raided the Lelang border and came back with captives.'],
        say: [['jinchung', '데려가라. 위례의 논밭을 일굴 손이다.', 'Bring them. These are hands to till the fields of Wirye.']] },
      { s: 'fortress', cast: ['yumu'],
        nar: ['낙랑태수 유무가 크게 노했다.', 'Liu Mao, Grand Administrator of Lelang, was furious.'],
        say: [['yumu', '백제의 이 무례를 반드시 갚아 주리라!', 'Baekje will pay for this insolence!']] },
      { s: 'palace', cast: ['goi'],
        nar: ['왕은 침공을 두려워하여 사로잡은 사람들을 돌려보냈다. 그러나 낙랑의 앙금은 남았다.',
              'Fearing an invasion, the king sent the captives home. But Lelang did not forget.'],
        say: [['goi', '…돌려보내라. 아직은 때가 아니다.', '…Send them back. The time is not yet.']] },
    ],
    gwangugeom: [
      { s: 'fortress', cast: ['guangui', 'wanggi'],
        nar: ['위의 유주자사 관구검이 현도태수 왕기를 앞세워 고구려로 쳐들어왔다.',
              'Guanqiu Jian, Inspector of You Province, invaded Goguryeo with Wang Qi of Xuantu leading the way.'],
        say: [['guangui', '환도성을 무너뜨려라.', 'Bring Hwando down.'],
              ['wanggi', '왕이 달아나면 끝까지 쫓겠습니다.', 'If the king flees, I will follow him to the end.']] },
      { s: 'fire', cast: ['dongcheon'], fx: ['쾅!', 'BOOM'],
        nar: ['환도성이 함락되고 동천왕은 동쪽 옥저 땅으로 달아났다.', 'Hwando fell, and King Dongcheon fled east into the land of Okjeo.'],
        say: [['dongcheon', '종묘를 지키지 못하다니…', 'I could not protect the ancestral shrine…']] },
      { s: 'mountain', cast: ['miru'],
        nar: ['추격이 턱밑까지 닿자 밀우가 결사대를 이끌고 돌아섰다.', 'When the pursuers were almost upon them, Miru turned back with a band sworn to die.'],
        say: [['miru', '대왕께서는 가십시오. 여기서 막겠습니다!', 'Go, Your Majesty. I will hold them here!']] },
      { s: 'battle', cast: ['yuyu', '@weigen'], fx: ['푹!', 'STAB'],
        nar: ['유유는 항복하는 척 음식을 들고 적진에 들어가, 그릇 속에 숨긴 칼로 적장을 찔렀다.',
              'Yuyu entered the enemy camp bearing food as if to surrender, and stabbed the enemy commander with a blade hidden in the dish.'],
        say: [['yuyu', '우리 왕께서 올리는 음식입니다—', 'A meal sent by my king—']] },
      { s: 'night', cast: ['dongcheon'],
        nar: ['적진이 흔들린 틈에 고구려군이 반격해 위군을 몰아냈다. 그러나 도성은 이미 잿더미였다.',
              'In the confusion Goguryeo struck back and drove the Wei army out. But the capital was already ash.'],
        say: [['dongcheon', '다시 쌓자. 무너진 것은 성벽뿐이다.', 'We rebuild. Only the walls have fallen.']] },
    ],
    okjeo_tribute: [
      { s: 'sea', cast: ['@okjeo'],
        nar: ['동옥저 사람들은 바다에서 소금과 물고기, 해초를 거두었다.', 'The people of East Okjeo gathered salt, fish and seaweed from the sea.'],
        say: [['@okjeo', '올해도 짐이 무겁구나.', 'The loads are heavy again this year.']] },
      { s: 'mountain',
        nar: ['그것을 지고 천 리 길을 걸어 고구려로 날랐다 한다.', 'They carried it on their backs, a thousand li on foot, to Goguryeo.'] },
      { s: 'palace', cast: ['@official'],
        nar: ['공물은 그 땅을 쥔 나라의 곳간을 채웠다.', 'The tribute filled the granaries of whoever held that land.'],
        say: [['@official', '옥저의 소금이 들어왔습니다.', 'The salt of Okjeo has arrived.']] },
    ],
    himiko: [
      { s: 'palace', cast: ['himiko'],
        nar: ['야마타이의 여왕 히미코는 귀신을 섬기며 백성을 다스렸다.', 'Himiko, queen of Yamatai, served the spirits and ruled her people through them.'],
        say: [['himiko', '내 뒤를… 누가 잇겠느냐…', 'Who… will follow me…']] },
      { s: 'grave',
        nar: ['여왕이 죽자 사람들은 지름 백여 보의 큰 무덤을 쌓았고, 따라 묻힌 종이 백여 명이었다.',
              'When she died they raised a great mound over a hundred paces across, and more than a hundred servants were buried with her.'] },
      { s: 'fire', cast: ['nanseungmi'], fx: ['챙!', 'CLASH'], snd: 'clang',
        nar: ['남자를 왕으로 세웠으나 나라가 따르지 않아, 서로 죽인 자가 천여 명이었다.',
              'A man was made king, but the land would not obey him, and more than a thousand died in the killing.'],
        say: [['nanseungmi', '이대로는 나라가 찢어진다!', 'This will tear the realm apart!']] },
      { s: 'ritual', cast: ['wa_iyeo'],
        nar: ['다시 히미코의 일족인 열세 살 소녀 이여를 세우고서야 나라가 잠잠해졌다.',
              'Only when Iyo, a thirteen-year-old girl of Himiko\'s clan, was made queen did the land grow quiet.'],
        say: [['wa_iyeo', '여왕의 뜻을 이어 가겠습니다.', 'I will carry on the queen\'s will.']] },
    ],
    buyeo_gone: [
      { s: 'field',
        nar: ['부여에 서리가 일찍 내려 들판의 곡식이 하얗게 얼어붙었다.', 'Frost came early to Buyeo, and the grain froze white in the fields.'] },
      { s: 'court', cast: ['@elder'],
        nar: ['부여의 옛 풍속에는 비바람이 고르지 못해 오곡이 여물지 않으면 그 허물을 왕에게 돌렸다.',
              'By the old custom of Buyeo, when rain and drought came out of season and the grain failed, the blame fell on the king.'],
        say: [['@elder', '하늘이 노했습니다. 왕을 바꾸어야 합니다.', 'Heaven is angry. The king must be replaced.']] },
      { s: 'palace', cast: ['mayeo'],
        nar: ['왕 마여는 곳간을 열어 백성을 달랬으나, 곡식은 절반만 남았다.', 'King Mayeo opened the granaries to calm the people, but only half the grain was left.'],
        say: [['mayeo', '곳간을 열어라. 굶는 자가 없게 하라.', 'Open the granaries. Let no one starve.']] },
    ],
    mucheon: [
      { s: 'ritual', cast: ['bulnaehu'],
        nar: ['시월, 예(濊) 사람들은 하늘에 제사를 올렸다.', 'In the tenth month, the people of Ye offered sacrifice to Heaven.'],
        say: [['bulnaehu', '하늘이여, 올해의 곡식을 받으소서.', 'Heaven, receive this year\'s grain.']] },
      { s: 'night', fx: ['둥! 둥!', 'DOOM DOOM'], snd: 'event',
        nar: ['밤낮으로 술 마시고 노래하며 춤추었으니, 이를 무천이라 하였다.', 'They drank, sang and danced day and night. This was called Mucheon, the Dance to Heaven.'] },
      { s: 'village',
        nar: ['축제가 끝나자 고을마다 웃음이 남았다.', 'When the festival ended, laughter lingered in every village.'] },
    ],

    // ────────────────────────────── 사료 사건 (새로 넣은 것)
    deungnae: [
      { s: 'court', cast: ['deungnae', 'dongcheon'],
        nar: ['신하 득래는 왕이 위와 등지는 것을 보고 여러 번 말렸다.', 'The minister Deungnae saw the king turning against Wei and warned him again and again.'],
        say: [['deungnae', '대국을 건드리시면 이 땅에 화가 미칩니다.', 'Provoke the great power and ruin will fall on this land.'],
              ['dongcheon', '물러가라. 과인의 뜻은 정해졌다.', 'Withdraw. Our mind is made up.']] },
      { s: 'night', cast: ['deungnae'],
        nar: ['왕이 끝내 듣지 않자 득래가 탄식했다.', 'When the king would not listen, Deungnae sighed.'],
        say: [['deungnae', '이 땅에 쑥대가 우거지는 것을 보게 되리라.', 'I shall see mugwort grow wild over this land.']] },
      { s: 'grave',
        nar: ['득래는 먹기를 끊고 굶어 죽었다.', 'Deungnae refused all food until he died.'] },
      { s: 'grave', cast: ['guangui'],
        nar: ['훗날 이 땅에 들어온 관구검은 그의 무덤을 헐지 말고 무덤가의 나무도 베지 말라 명했다.',
              'Later, when Guanqiu Jian marched in, he ordered that the grave not be disturbed and that no tree beside it be cut.'],
        say: [['guangui', '충신의 무덤이다. 손대지 마라.', 'This is the grave of a loyal man. Leave it be.']] },
    ],
    pyeongyang247: [
      { s: 'fire', cast: ['dongcheon'],
        nar: ['환도성은 전쟁으로 무너져 다시 도읍으로 삼기 어려웠다.', 'War had ruined Hwando, and it could no longer serve as the capital.'],
        say: [['dongcheon', '이 폐허에서는 다시 일어설 수 없다.', 'We cannot rise again from these ruins.']] },
      { s: 'fortress', cast: ['myeongnim'], fx: ['쿵! 쿵!', 'THUD THUD'],
        nar: ['왕은 평양성을 쌓고 백성과 종묘사직을 옮겼다.', 'The king built Pyongyang Fortress and moved his people and the ancestral shrines there.'],
        say: [['myeongnim', '성벽이 한 자씩 올라갑니다!', 'The wall rises a foot at a time!']] },
      { s: 'map',
        nar: ['이 평양이 지금의 평양인지는 학설이 갈린다. 장수왕의 평양 천도(427)보다 백팔십 년 앞선 일이기 때문이다.',
              'Scholars disagree on whether this was today\'s Pyongyang — it came 180 years before King Jangsu moved the capital there in 427.'] },
    ],
    bulnae247: [
      { s: 'fortress', cast: ['bulnaehu', 'yumu'],
        nar: ['두 해 전 낙랑과 대방의 군사가 고개 동쪽의 예를 쳤고, 불내후는 고을을 들어 항복했다.',
              'Two years earlier, the armies of Lelang and Daifang had struck the Ye beyond the ridge, and the Lord of Bulnae surrendered his towns.'],
        say: [['yumu', '위를 따르면 그대의 고을은 지켜 주겠다.', 'Follow Wei and your towns will be spared.']] },
      { s: 'court', cast: ['bulnaehu'],
        nar: ['정시 8년, 불내후가 위의 궁궐에 이르러 조공하니 황제가 그를 불내예왕으로 봉했다.',
              'In the eighth year of Zhengshi, the Lord of Bulnae came to the Wei court with tribute, and the emperor named him King of Bulnae-Ye.'],
        say: [['bulnaehu', '사철마다 군에 나아가 예를 갖추겠습니다.', 'I will come to the commandery in every season to pay my respects.']] },
      { s: 'village',
        nar: ['왕이라는 이름을 받았으나, 그는 백성 사이에 섞여 살았다 한다.', 'He bore the title of king, yet it is said he lived among the common folk.'] },
    ],
    zhangzheng247: [
      { s: 'sea', cast: ['himiko', 'himikuko'],
        nar: ['왜의 여왕 히미코와 구노국의 남왕 히미쿠코는 본래 사이가 나빴다.',
              'Himiko, queen of Wa, and Himikuko, the male king of Kunu, had long been at odds.'],
        say: [['himikuko', '여왕의 나라를 무너뜨려라!', 'Tear down the queen\'s realm!']] },
      { s: 'court', cast: ['@wa_envoy', 'wanggi'],
        nar: ['히미코는 사신을 대방군에 보내 서로 싸우는 형편을 알렸다. 마침 태수 왕기가 새로 부임해 있었다.',
              'Himiko sent envoys to Daifang to report the fighting. Wang Qi had just arrived as Grand Administrator.'],
        say: [['@wa_envoy', '구노국이 여왕의 나라를 치고 있습니다.', 'Kunu is attacking the queen\'s realm.']] },
      { s: 'sea', cast: ['@zhangzheng', 'nanseungmi'],
        nar: ['위는 장정을 보내 조서와 누런 깃발을 난승미에게 주고, 격문을 지어 타일렀다.',
              'Wei sent Zhang Zheng to give Nashime an imperial edict and a yellow banner, and to admonish them with a proclamation.'],
        say: [['@zhangzheng', '황제께서 여왕의 편에 서셨소.', 'The emperor stands with the queen.'],
              ['nanseungmi', '황제의 깃발이다! 군사들의 기운이 오르리라.', 'The emperor\'s banner! Our soldiers\' spirits will soar.']] },
    ],
    hwachin248: [
      { s: 'court', cast: ['cheomhae'],
        nar: ['첨해가 사로의 왕위에 오른 이듬해, 사로는 고구려에 사신을 보냈다.',
              'The year after Cheomhae took the throne of Saro, Saro sent envoys to Goguryeo.'],
        say: [['cheomhae', '북쪽이 조용해야 남쪽을 돌볼 수 있다.', 'The north must be quiet if we are to tend the south.']] },
      { s: 'mountain', cast: ['@silla_envoy'],
        nar: ['사신은 험한 고개를 넘어 북쪽으로 향했다.', 'The envoys crossed the steep passes heading north.'],
        say: [['@silla_envoy', '두 나라가 칼을 거두기를 청합니다.', 'We ask that our two kingdoms sheathe their swords.']] },
      { s: 'palace', cast: ['dongcheon'],
        nar: ['전쟁에 지친 고구려도 손을 내밀었다. 두 나라가 화친을 맺었다.', 'Goguryeo, weary of war, took the offered hand. The two kingdoms made peace.'],
        say: [['dongcheon', '좋다. 동쪽의 벗이 되자.', 'Very well. Let us be friends in the east.']] },
    ],
    dongcheon248: [
      { s: 'palace', cast: ['dongcheon', 'gy_yeonbul'],
        nar: ['동천왕이 병들어 누웠다.', 'King Dongcheon lay gravely ill.'],
        say: [['dongcheon', '연불아… 무너진 나라를 네가 다시 세워라.', 'Yeonbul… you must rebuild what has fallen.'],
              ['gy_yeonbul', '아바마마…', 'Father…']] },
      { s: 'grave',
        nar: ['왕이 죽자 그 은덕을 그리워하여 따라 죽으려는 신하가 많았다.', 'When the king died, many of his close servants, remembering his kindness, sought to die with him.'] },
      { s: 'grave', cast: ['gy_yeonbul'],
        nar: ['새 왕이 예가 아니라며 막았으나, 장례날 무덤에 와서 스스로 목숨을 끊는 이가 많았다.',
              'The new king forbade it as against the rites, yet on the day of the burial many took their own lives at the tomb.'],
        say: [['gy_yeonbul', '따라 죽는 것은 예가 아니다. 살아서 나라를 지켜라!', 'Following in death is not the rite. Live, and guard the kingdom!']] },
      { s: 'grave',
        nar: ['사람들은 땔나무를 베어 그 주검들을 덮었고, 그곳을 시원(柴原)이라 불렀다.',
              'People cut firewood to cover the bodies, and called the place Siwon — the Field of Firewood.'] },
    ],
    seokuro249: [
      { s: 'palace', cast: ['seokuro', '@galnago'],
        nar: ['왜의 사신 갈나고가 사로에 와 머물렀다. 석우로가 그를 대접했다.', 'Galnago, an envoy of Wa, came to stay in Saro. Seok Uro hosted him.'],
        say: [['seokuro', '(웃으며) 조만간 너희 왕을 소금 굽는 종으로, 왕비는 밥 짓는 여자로 삼겠소.',
               '(laughing) One of these days I\'ll make your king a salt-boiling slave, and your queen a kitchen maid.'],
              ['@galnago', '…….', '……']] },
      { s: 'sea', cast: ['@wa_general'], fx: ['와아!', 'RAAAH!'], snd: 'warcry',
        nar: ['그 말을 전해 들은 왜왕이 노하여 장군 우도주군을 보내 사로를 쳤다.', 'Hearing of it, the Wa king flew into a rage and sent the general Udojugun against Saro.'] },
      { s: 'fortress', cast: ['seokuro'],
        nar: ['석우로는 스스로 적진으로 걸어갔다.', 'Seok Uro walked into the enemy camp himself.'],
        say: [['seokuro', '내 혀가 부른 화다. 내가 가서 풀겠다.', 'My tongue brought this on us. I will go and undo it.']] },
      { s: 'fire', cast: ['@wa_general'],
        nar: ['왜인들은 그를 붙잡아 장작 위에 올려 불태워 죽이고 돌아갔다.', 'The Wa seized him, burned him on a pyre, and went home.'] },
      { s: 'night',
        nar: ['삼국사기 신라본기는 이 일을 첨해왕 3년(249)에, 석우로 열전은 7년(253)에 적었다.',
              'The Silla Annals of the Samguk Sagi date this to 249; Seok Uro\'s biography in the same book puts it in 253.'] },
    ],
    gwanna251: [
      { s: 'palace', cast: ['gy_yeonbul', '@gwanna'],
        nar: ['중천왕은 관나부 출신의 부인을 몹시 아꼈다. 얼굴이 곱고 머리카락이 아홉 자나 되었다 한다.',
              'King Jungcheon adored a lady of the Gwanna clan. She was lovely, and her hair was said to be nine feet long.'],
        say: [['gy_yeonbul', '그대를 소후로 삼으리라.', 'I will make you my lesser queen.']] },
      { s: 'court', cast: ['@queenyeon'],
        nar: ['왕후 연씨가 이를 걱정했다.', 'Queen Yeon grew worried.'],
        say: [['@queenyeon', '위에서 천금을 주고 긴 머리 여인을 구한다 하니, 그 여인을 보내면 다시는 쳐들어오지 않을 것입니다.',
               'Wei pays a thousand in gold for long-haired women. Send her there, and they will never invade again.']] },
      { s: 'mountain', cast: ['@gwanna', 'gy_yeonbul'],
        nar: ['관나부인은 사냥에서 돌아오는 왕을 가죽 주머니를 들고 맞으며 울면서 왕후를 모함했다.',
              'Lady Gwanna met the king returning from the hunt with a leather sack in her hands, and wept as she slandered the queen.'],
        say: [['@gwanna', '왕후께서 저를 이 주머니에 넣어 바다에 던지려 합니다!', 'The queen means to stuff me in this sack and throw me into the sea!']] },
      { s: 'sea', cast: ['gy_yeonbul'],
        nar: ['거짓임을 안 왕은 노하여, 도리어 관나부인을 그 주머니에 넣어 서해에 던지게 했다.',
              'The king saw through the lie and, in his anger, had Lady Gwanna herself put into that sack and cast into the western sea.'],
        say: [['gy_yeonbul', '네가 들고 온 주머니다.', 'It is the sack you brought.']] },
    ],
    goegok255: [
      { s: 'fortress', cast: ['goi'],
        nar: ['백제가 군사를 일으켜 사로를 쳤다.', 'Baekje raised an army and attacked Saro.'],
        say: [['goi', '사로의 서쪽 고을을 거두어라.', 'Take the western towns of Saro.']] },
      { s: 'battle', cast: ['@ikjong'], fx: ['챙!', 'CLASH'], snd: 'clang',
        nar: ['사로의 일벌찬 익종이 괴곡 서쪽에서 맞서 싸웠다.', 'Ikjong, an ilbeolchan of Saro, met them west of Goegok.'],
        say: [['@ikjong', '여기서 물러서면 금성이 위태롭다!', 'If we fall back here, Geumseong is in danger!']] },
      { s: 'fire',
        nar: ['익종은 이 싸움에서 전사했다. 두 나라 사이에 피가 흘렀다.', 'Ikjong fell in the battle. Blood now lay between the two kingdoms.'] },
    ],
    yangmaek259: [
      { s: 'fortress', cast: ['@weijihai'],
        nar: ['위의 장수 위지해가 군사를 이끌고 고구려로 쳐들어왔다.', 'The Wei general Yuchi Kai led an army into Goguryeo.'],
        say: [['@weijihai', '관구검 장군이 못다 한 일을 끝내리라.', 'I will finish what General Guanqiu began.']] },
      { s: 'palace', cast: ['gy_yeonbul'],
        nar: ['중천왕은 정예 기병 오천을 골랐다.', 'King Jungcheon picked five thousand elite horsemen.'],
        say: [['gy_yeonbul', '양맥의 골짜기로 끌어들여라.', 'Draw them into the valleys of Yangmaek.']] },
      { s: 'battle', fx: ['와아!', 'CHARGE!'], snd: 'warcry',
        nar: ['고구려 기병이 골짜기에서 위군을 쳐부수고 팔천여 명의 목을 베었다.', 'The Goguryeo cavalry smashed the Wei army in the valley and took more than eight thousand heads.'] },
      { s: 'night', cast: ['gy_yeonbul'],
        nar: ['환도성이 불탄 지 열세 해. 고구려는 다시 일어섰음을 보였다.', 'Thirteen years after Hwando burned, Goguryeo showed that it had risen again.'],
        say: [['gy_yeonbul', '아버님, 보고 계십니까.', 'Father, are you watching?']] },
    ],
    goi260: [
      { s: 'court', cast: ['goi'],
        nar: ['나랏일이 커지자 고이왕은 벼슬을 새로 짰다.', 'As the affairs of state grew, King Goi reorganized his officials.'],
        say: [['goi', '여섯 좌평이 각기 맡은 일을 다스리게 하라.', 'Let six jwapyeong each govern their own charge.']] },
      { s: 'court', cast: ['jinmul', 'usu'],
        nar: ['삼국사기는 이때 여섯 좌평과, 좌평에서 극우까지 열여섯 관등을 두었다고 적었다.',
              'The Samguk Sagi records that he now set six jwapyeong ministers and sixteen ranks, from jwapyeong down to geugu.'],
        say: [['jinmul', '이제 누가 무엇을 맡는지 분명해졌습니다.', 'Now it is clear who answers for what.']] },
      { s: 'palace', cast: ['goi'],
        nar: ['백제는 마한의 한 나라에서 스스로 다스리는 나라로 한 걸음 나아갔다.',
              'Baekje took a step from being one state among Mahan toward a kingdom that governed itself.'] },
    ],
    goi262: [
      { s: 'market', cast: ['@corrupt'],
        nar: ['관리들 가운데 뇌물을 받고 나라 곡식을 빼돌리는 자가 있었다.', 'Some officials took bribes and siphoned off the state\'s grain.'],
        say: [['@corrupt', '이만하면 아무도 모를 것이다.', 'No one will ever notice this much.']] },
      { s: 'court', cast: ['goi'],
        nar: ['고이왕이 영을 내렸다.', 'King Goi issued a decree.'],
        say: [['goi', '재물을 받거나 도둑질한 관리는 장물의 세 배를 물리고, 평생 벼슬길을 막아라!',
               'Any official who takes bribes or steals shall repay threefold and be barred from office for life!']] },
      { s: 'village',
        nar: ['고을의 창고가 다시 채워지고 백성의 원망이 잦아들었다.', 'The county storehouses filled again, and the people\'s grumbling died away.'] },
    ],
    jin265: [
      { s: 'palace', cast: ['@simayan'],
        nar: ['위의 조정은 이미 사마씨의 손에 있었다.', 'The Wei court had long been in the hands of the Sima clan.'],
        say: [['@simayan', '천명은 위를 떠났다. 오늘부터 나라 이름은 진(晉)이다.', 'Heaven\'s mandate has left Wei. From today the realm is called Jin.']] },
      { s: 'court',
        nar: ['위의 마지막 황제가 자리를 내주고, 사마염이 진을 세웠다.', 'The last Wei emperor gave up the throne, and Sima Yan founded the Jin dynasty.'] },
      { s: 'fortress', cast: ['@lelang_off'],
        nar: ['먼 동쪽 낙랑과 대방의 군사들은 흔들렸다.', 'Far to the east, the garrisons of Lelang and Daifang wavered.'],
        say: [['@lelang_off', '황제가 바뀌었다니… 우리는 누구를 위해 싸우는가?', 'A new emperor… then who are we fighting for?']] },
      { s: 'map',
        nar: ['이 게임에서는 위 세력이 이름을 그대로 둔 채 진을 잇는다.', 'In this game the Wei faction keeps its name and carries on as Jin.'] },
    ],

    // ────────────────────────────── 가상 이야기 (창작)
    f_minyu: [
      { s: 'mountain', cast: ['@bandit'],
        nar: ['대관령 고갯길에 산적 떼가 들끓어 하슬라로 가는 소금 수레가 끊겼다.', 'Bandits swarmed the Daegwallyeong pass, and the salt carts to Haseulla stopped coming.'],
        say: [['@bandit', '짐은 두고 목숨만 가져가라!', 'Leave the goods and keep your lives!']] },
      { s: 'mountain', cast: ['kimminyu'], fx: ['휙!', 'WHOOSH'],
        nar: ['그때 창 한 자루를 든 젊은이가 고개 위에서 뛰어내렸다.', 'Just then a young man with a spear leapt down from the ridge.'],
        say: [['kimminyu', '길을 막는 자는 나부터 넘어야 할 것이다.', 'Whoever blocks this road must get past me first.']] },
      { s: 'battle', cast: ['kimminyu', '@bandit'], fx: ['챙! 챙!', 'CLANG!'], snd: 'clang',
        nar: ['창끝이 한 번 돌 때마다 산적이 하나씩 쓰러졌다.', 'With every turn of his spear, another bandit fell.'],
        say: [['@bandit', '이, 이놈은 사람이 아니다!', 'Th-this one isn\'t human!']] },
      { s: 'village', cast: ['kimminyu'],
        nar: ['고을 사람들이 이름을 묻자 그는 짧게 답하고 바닷가로 사라졌다.', 'When the villagers asked his name, he answered briefly and vanished toward the shore.'],
        say: [['kimminyu', '강릉의 김민유. 필요하면 다시 찾으시오.', 'Kim Min-yu of Gangneung. Come find me if you need me.']] },
    ],
    f_jeongchan: [
      { s: 'village', cast: ['@farmer'],
        nar: ['보릿고개가 오자 중원경의 고을마다 솥이 비었다.', 'When the spring famine came, the pots stood empty in every village of Jungwongyeong.'],
        say: [['@farmer', '보리가 익으려면 아직 한 달인데…', 'The barley needs another month…']] },
      { s: 'market', cast: ['jeongchan'],
        nar: ['아전 정찬이 오래 적어 온 장부를 펼쳤다.', 'The clerk Jeong Chan opened the ledger he had kept for years.'],
        say: [['jeongchan', '풍년마다 한 되씩 덜어 둔 곡식이 서쪽 창고에 있습니다.', 'Grain set aside a measure at a time in good years sits in the west storehouse.']] },
      { s: 'village', cast: ['jeongchan', '@farmer'],
        nar: ['창고 문이 열리자 줄이 고개 너머까지 이어졌다.', 'When the storehouse doors opened, the line stretched over the hill.'],
        say: [['@farmer', '정 아전 덕에 올봄을 넘깁니다!', 'Thanks to Clerk Jeong we\'ll get through this spring!'],
              ['jeongchan', '빌려 드리는 것입니다. 가을에 갚으시면 됩니다.', 'It is a loan. Repay it in autumn.']] },
    ],
    f_forge: [
      { s: 'forge', cast: ['kimgyeongho'], fx: ['땅! 땅!', 'CLANG CLANG'], snd: 'clang',
        nar: ['북원의 대장간에서 밤새 망치 소리가 그치지 않았다.', 'All night long the hammer never stopped in the smithy of Bugwon.'],
        say: [['kimgyeongho', '쇠는 거짓말을 안 한다. 두드린 만큼 단단해지지.', 'Iron doesn\'t lie. It hardens as much as you strike it.']] },
      { s: 'forge', cast: ['@apprentice'],
        nar: ['그가 벼린 창은 휘어지지 않았고, 소문을 들은 장정들이 모여들었다.', 'The spears he forged never bent, and young men gathered when they heard.'],
        say: [['@apprentice', '저희도 그 창을 들고 싸우게 해 주십시오!', 'Let us fight with those spears too!']] },
      { s: 'fortress', cast: ['kimgyeongho'],
        nar: ['그날로 창을 든 장정 팔백이 북원성 군적에 이름을 올렸다.', 'That very day eight hundred men with spears put their names on the rolls of Bugwon.'],
        say: [['kimgyeongho', '글은 몰라도 창 쓰는 법은 가르쳐 주마.', 'I can\'t read, but I can teach you the spear.']] },
    ],
    f_archery: [
      { s: 'river', cast: ['@judge'],
        nar: ['오월 씨뿌리기를 마친 뒤, 한수 가에서 활쏘기 겨루기가 열렸다.', 'After the May sowing, an archery contest was held on the banks of the Han.'],
        say: [['@judge', '과녁은 백 보 밖 버들잎이다!', 'The target: a willow leaf a hundred paces off!']] },
      { s: 'river', cast: ['johyeonjin'], fx: ['팽!', 'THWANG'],
        nar: ['사내들이 줄줄이 빗나간 뒤, 한 여인이 활을 들었다.', 'After man after man had missed, a woman raised her bow.'],
        say: [['johyeonjin', '바람이 멎기를 기다리면 됩니다.', 'You only have to wait for the wind to die.']] },
      { s: 'village', cast: ['johyeonjin', '@judge'],
        nar: ['화살은 버들잎 한가운데를 꿰뚫었고, 강가가 함성으로 뒤덮였다.', 'The arrow pierced the heart of the leaf, and the riverbank erupted in cheers.'],
        say: [['@judge', '위례의 조현진, 으뜸이오!', 'Jo Hyeon-jin of Wirye takes first place!']] },
    ],
    f_plague: [
      { s: 'village', cast: ['@sick'],
        nar: ['{castle}에 열병이 돌기 시작했다.', 'A fever began to spread through {castle}.'],
        say: [['@sick', '몸이 불덩이 같소…', 'I\'m burning up…']] },
      { s: 'night', cast: ['@shaman'],
        nar: ['무당이 굿을 벌였지만 앓는 이는 날마다 늘었다.', 'The shaman performed her rites, yet more fell sick each day.'],
        say: [['@shaman', '역신이 들었다! 문마다 붉은 흙을 발라라!', 'A plague spirit has come! Smear red clay on every door!']] },
      { s: 'village', cast: ['kimyujin'],
        nar: ['금성의 서고에서 자란 김유진이 옛 의서를 들고 나섰다.', 'Kim Yu-jin, raised among the scrolls of Geumseong, came forward with an old medical text.'],
        say: [['kimyujin', '앓는 이의 그릇과 옷은 따로 쓰게 하고, 약초를 달여 먹이세요.', 'Give the sick their own bowls and clothes, and brew them herbs.']] },
      { s: 'field',
        nar: ['가을바람이 불 무렵에야 열병이 물러갔다.', 'Only when the autumn wind blew did the fever retreat.'] },
    ],
    f_pirates: [
      { s: 'sea', cast: ['@pirate'], fx: ['쾅!', 'CRASH'],
        nar: ['구야의 포구에 해적선이 들이닥쳐 철을 실은 배를 털어 갔다.', 'Pirate ships raided the harbor of Guya and plundered the iron barges.'],
        say: [['@pirate', '쇠덩이를 몽땅 실어라!', 'Load up every ingot!']] },
      { s: 'sea', cast: ['jogyeongjun'],
        nar: ['뱃사람 조경준이 물때를 헤아렸다.', 'The sailor Jo Gyeong-jun reckoned the tides.'],
        say: [['jogyeongjun', '썰물이 시작되면 저놈들 배는 모래톱에 걸린다.', 'When the tide goes out, their ships will stick on the sandbar.']] },
      { s: 'sea', cast: ['jogyeongjun', '@pirate'], fx: ['피융!', 'FWOOSH'],
        nar: ['모래톱에 걸린 해적선 위로 불화살이 비처럼 쏟아졌다.', 'Fire arrows rained down on the pirate ships stranded on the sand.'],
        say: [['@pirate', '배가 움직이지 않는다!', 'The ship won\'t move!']] },
      { s: 'market', cast: ['jogyeongjun'],
        nar: ['빼앗긴 철을 되찾았고, 해적선에 실린 재물까지 고을 창고로 들어왔다.', 'The iron was recovered, and the pirates\' own loot went into the town storehouse.'],
        say: [['jogyeongjun', '바다는 아는 사람 편입니다.', 'The sea sides with those who know it.']] },
    ],
    f_comet: [
      { s: 'sky',
        nar: ['어느 밤, 꼬리가 긴 살별이 동북 하늘을 가로질렀다.', 'One night a long-tailed comet crossed the northeastern sky.'] },
      { s: 'village', cast: ['@elder'],
        nar: ['사람들은 하늘을 올려다보며 수군거렸다.', 'People looked up and whispered.'],
        say: [['@elder', '살별은 난리가 올 징조라 했소.', 'They say a comet foretells war.']] },
      { s: 'palace', cast: ['{lord}'],
        nar: ['{fac}의 군주가 신하들을 불러 모았다.', 'The ruler of {fac} summoned the court.'],
        say: [['{lord}', '하늘의 뜻은 사람이 만든다. 성을 살피고 백성을 달래라.', 'Men make the will of Heaven. Inspect the walls and calm the people.']] },
    ],
    f_bandits: [
      { s: 'night', cast: ['@bandit'], fx: ['불이야!', 'FIRE!'],
        nar: ['{castle} 바깥에 도적 떼가 일어나 창고에 불을 질렀다.', 'Bandits rose outside {castle} and set the storehouses ablaze.'],
        say: [['@bandit', '관가의 곡식은 우리 것이다!', 'The magistrate\'s grain is ours!']] },
      { s: 'mountain', cast: ['seojongbeom'],
        nar: ['무진의 기마 서종범이 소식을 듣고 말을 달렸다.', 'Seo Jong-beom, the horseman of Mujin, heard the news and rode hard.'],
        say: [['seojongbeom', '밤길이라도 내 말은 길을 잃지 않소!', 'Night or not, my horse never loses the road!']] },
      { s: 'battle', cast: ['seojongbeom', '@bandit'], fx: ['히히힝!', 'NEIGH!'],
        nar: ['말발굽 소리에 도적들이 산으로 흩어졌다.', 'At the thunder of hooves the bandits scattered into the hills.'],
        say: [['@bandit', '기마다! 달아나라!', 'Horsemen! Run!']] },
    ],
    f_market: [
      { s: 'market', cast: ['choiinu'],
        nar: ['개성에 낙랑과 마한의 상인이 함께 모이는 큰 장이 섰다.', 'A great fair opened at Gaeseong, where merchants of Lelang and Mahan came together.'],
        say: [['choiinu', '소금은 이쪽, 비단은 저쪽! 줄을 서시오!', 'Salt this way, silk that way! Form a line!']] },
      { s: 'market', cast: ['@merchant'],
        nar: ['두 곳 말을 다 하는 최인우가 흥정을 붙이자 다툼이 사라졌다.', 'Choi In-u spoke both tongues, and once he brokered the deals the quarrels vanished.'],
        say: [['@merchant', '말이 통하니 값도 통하는구려.', 'When the words match, so do the prices.']] },
      { s: 'village', cast: ['choiinu'],
        nar: ['장이 끝나자 고을 금고가 묵직해졌다.', 'When the fair closed, the town treasury was heavy with coin.'],
        say: [['choiinu', '장사는 서로 남아야 오래갑니다.', 'Trade lasts only when both sides profit.']] },
    ],
    f_hunt: [
      { s: 'mountain', cast: ['@hunter'],
        nar: ['한겨울, 함주 고을에 사람을 해치는 큰 곰이 내려왔다.', 'In the dead of winter a great man-eating bear came down on the villages of Hamju.'],
        say: [['@hunter', '벌써 소 세 마리를 잃었소!', 'We\'ve already lost three oxen!']] },
      { s: 'mountain', cast: ['hamjunwon'],
        nar: ['홑옷 차림의 사냥꾼 함준원이 눈 위의 자취를 읽었다.', 'Ham Jun-won, a hunter in a single thin coat, read the tracks in the snow.'],
        say: [['hamjunwon', '한 식경 전에 지나갔군. 멀리 못 갔소.', 'It passed not long ago. It hasn\'t gone far.']] },
      { s: 'mountain', cast: ['hamjunwon'], fx: ['크아앙!', 'ROAR!'],
        nar: ['곰과 사냥꾼이 눈보라 속에서 맞붙었다.', 'Bear and hunter clashed in the blizzard.'],
        say: [['hamjunwon', '덤벼라!', 'Come on!']] },
      { s: 'village', cast: ['hamjunwon', '@hunter'],
        nar: ['사냥꾼이 곰 가죽을 끌고 내려오자 고을에 잔치가 벌어졌다.', 'When the hunter came down dragging the bearskin, the village threw a feast.'],
        say: [['@hunter', '오늘은 고기 굽는 냄새가 온 고을에 퍼지는구려!', 'Today the whole village smells of roasting meat!']] },
    ],
  };

  // 그 사건 때의 호칭 — 명단 이름(즉위 전 이름)과 나레이션의 호칭이 어긋나지 않게
  const ALIAS = {
    gwanna251:   { gy_yeonbul: ['중천왕', 'King Jungcheon'] },
    yangmaek259: { gy_yeonbul: ['중천왕', 'King Jungcheon'] },
    hwachin248:  { cheomhae: ['첨해이사금', 'King Cheomhae'] },
    dongcheon248: { gy_yeonbul: ['태자 연불', 'Crown Prince Yeonbul'] },
  };

  window.SamhanStory = { STORY, EXTRAS, ALIAS };
})();
